project_id = "twfzlbockonxopuindaw"

[api]
  enabled = true
  extra_search_path = ["public", "extensions"]
  max_rows = 1000
  port = 54321
  schemas = ["public", "graphql_public"]

[auth]
  additional_redirect_urls = ["https://lovable.dev"]
  enabled = true
  jwt_expiry = 3600
  site_url = "http://localhost:3000"
  [auth.email]
    double_confirm_changes = true
    max_frequency = "1s"

[db]
  port = 54322

[functions]
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.check-open-answer]
    verify_jwt = false
  [functions.exam-auto-submit-expired]
    verify_jwt = false
  [functions.generate-adaptive-question]
    verify_jwt = false
  [functions.generate-quests]
    verify_jwt = false
  [functions.generate-study-plan]
    verify_jwt = false
  [functions.send-invitation-accepted-email]
    verify_jwt = false
  [functions.send-invitation-email]
    verify_jwt = false
  [functions.send-verification-email]
    verify_jwt = false
  [functions.send-principal-weekly-digest]
    verify_jwt = false
  [functions.submit-demo-request]
    verify_jwt = false
  [functions.validate-student-invitation]
    verify_jwt = false
  [functions.validate-invite]
    verify_jwt = false
  [functions.accept-invite]
    verify_jwt = false

[storage]
  enabled = true
  file_size_limit = "100MiB"

[studio]
  enabled = true
  port = 54323
