
import React, { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'en' | 'es' | 'fr' | 'de' | 'zh' | 'ja' | 'pt' | 'it' | 'ru' | 'ar';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations: Record<Language, Record<string, string>> = {
  en: {
    'hero.title': 'Transform Education with AI-Powered Learning',
    'hero.subtitle': 'Personalized, adaptive learning experiences that grow with every student. Harness the power of AI to unlock potential and accelerate academic success.',
    'cta.start': 'Start Learning',
    'cta.demo': 'Try Demo',
    'nav.features': 'Features',
    'nav.pricing': 'Pricing',
    'nav.about': 'About',
    'nav.contact': 'Contact',
    
    // Auth translations
    'auth.title': 'Welcome to TeachlyAI',
    'auth.subtitle': 'Join thousands of students and educators transforming learning with AI',
    'auth.signInTab': 'Sign In',
    'auth.signUpTab': 'Sign Up',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.confirmPassword': 'Confirm Password',
    'auth.signInButton': 'Sign In',
    'auth.signUpButton': 'Sign Up',
    'auth.googleSignIn': 'Continue with Google',
    'auth.noAccount': "Don't have an account?",
    'auth.hasAccount': 'Already have an account?',
    'auth.signUpLink': 'Sign up here',
    'auth.signInLink': 'Sign in here',
    'auth.errors.invalidCredentials': 'Invalid email or password',
    'auth.errors.emailInUse': 'Email is already in use',
    'auth.errors.passwordMismatch': 'Passwords do not match',
    'auth.errors.weakPassword': 'Password must be at least 6 characters',
    'auth.errors.genericError': 'An error occurred. Please try again.',
    
    // Common
    'common.loading': 'Loading...',
    
    // Chat interface
    'chat.title': 'AI Tutor',
    'chat.placeholder': 'Type your message here...',
    'chat.send': 'Send',
    'chat.newChat': 'New Chat',
    'chat.previousChats': 'Previous Chats',
    'chat.progress': 'Progress',
    'chat.tokensUsed': 'tokens used',
    'chat.thinking': 'AI is thinking...',
    'chat.monitoring': 'Monitoring',
    
    // Features section
    'features.section.title': 'Powerful Features for Modern Education',
    'features.section.subtitle': 'Our AI-driven platform adapts to each student\'s unique learning style and pace',
    'features.adaptive.title': 'Adaptive Learning',
    'features.adaptive.desc': 'AI algorithms adjust difficulty and content based on student performance and learning patterns.',
    'features.voice.title': 'Voice Interaction',
    'features.voice.desc': 'Natural voice conversations make learning more engaging and accessible for all students.',
    'features.content.title': 'Smart Content',
    'features.content.desc': 'Automatically generated quizzes, explanations, and practice problems tailored to each topic.',
    'features.gamified.title': 'Gamified Learning',
    'features.gamified.desc': 'Achievement systems, progress tracking, and rewards keep students motivated and engaged.',
    'features.analytics.title': 'Real-time Analytics',
    'features.analytics.desc': 'Comprehensive insights into learning progress, strengths, and areas for improvement.',
    'features.collaborative.title': 'Collaborative Tools',
    'features.collaborative.desc': 'Connect students, teachers, and parents with shared dashboards and communication tools.',
    
    // All other existing translations...
    'subjects.title': 'Comprehensive Subject Coverage',
    'subjects.subtitle': 'From elementary to advanced levels, our AI adapts to teach any subject effectively',
    'subjects.mathematics.title': 'Mathematics',
    'subjects.mathematics.desc': 'Algebra, Geometry, Calculus & more',
    'subjects.sciences.title': 'Sciences',
    'subjects.sciences.desc': 'Physics, Chemistry, Biology & Earth Science',
    'subjects.literature.title': 'Literature',
    'subjects.literature.desc': 'Reading, Writing & Language Arts',
    'subjects.social.title': 'Social Studies',
    'subjects.social.desc': 'History, Geography & Civics',
    'subjects.technology.title': 'Technology',
    'subjects.technology.desc': 'Computer Science & Digital Literacy',
    'subjects.arts.title': 'Arts',
    'subjects.arts.desc': 'Visual Arts, Music & Creative Expression',
    'subjects.languages.title': 'Languages',
    'subjects.languages.desc': 'Foreign Languages & Communication',
    'subjects.health.title': 'Health & PE',
    'subjects.health.desc': 'Physical Education & Wellness',
    'advanced.title': 'Advanced AI Features',
    'advanced.adaptive.title': 'Personalized Learning Paths',
    'advanced.adaptive.desc': 'Our AI creates unique learning journeys tailored to each student\'s strengths, weaknesses, and interests.',
    'advanced.feedback.title': 'Instant Feedback',
    'advanced.feedback.desc': 'Real-time corrections and suggestions help students learn from mistakes immediately.',
    'advanced.safe.title': 'Safe Learning Environment',
    'advanced.safe.desc': 'Child-safe AI with content filtering and appropriate learning materials for all ages.',
    'advanced.availability.title': '24/7 Availability',
    'advanced.availability.desc': 'Learning never stops with round-the-clock AI tutoring and support.',
    'achievement.title': 'Track Your Progress',
    'achievement.desc': 'Monitor learning achievements and celebrate milestones',
    'achievement.streak': 'Learning Streak',
    'achievement.progress': 'Growing!',
    'achievement.problems': 'Problems Solved',
    'achievement.tracking': 'Tracking',
    'achievement.level': 'Knowledge Level',
    'achievement.growing': 'Growing',
    'testimonials.title': 'What Educators Are Saying',
    'testimonials.subtitle': 'Join thousands of satisfied teachers, students, and parents',
    'testimonials.teacher': 'High School Teacher',
    'testimonials.teacher.content': 'TeachlyAI has revolutionized my classroom. Students are more engaged and their test scores have improved dramatically.',
    'testimonials.parent': 'Parent of 3',
    'testimonials.parent.content': 'My children actually look forward to studying now. The personalized approach really works for different learning styles.',
    'testimonials.principal': 'School Principal',
    'testimonials.principal.content': 'The analytics and insights have helped us identify learning gaps and improve our curriculum significantly.',
    'pricing.title': 'Choose Your Plan',
    'pricing.subtitle': 'Flexible pricing for individuals, families, and schools',
    'pricing.individual': 'Individual',
    'pricing.individual.price': '$9.99',
    'pricing.month': '/month',
    'pricing.individual.feature1': 'Unlimited AI tutoring',
    'pricing.individual.feature2': 'Progress tracking',
    'pricing.individual.feature3': 'Basic analytics',
    'pricing.individual.feature4': 'Email support',
    'pricing.family': 'Family',
    'pricing.family.price': '$19.99',
    'pricing.family.feature1': 'Up to 6 student accounts',
    'pricing.family.feature2': 'Parent dashboard',
    'pricing.family.feature3': 'Advanced analytics',
    'pricing.family.feature4': 'Priority support',
    'pricing.school': 'School',
    'pricing.school.price': 'Custom',
    'pricing.school.feature1': 'Unlimited students',
    'pricing.school.feature2': 'Admin dashboard',
    'pricing.school.feature3': 'Custom curriculum',
    'pricing.school.feature4': 'Dedicated support',
    'pricing.most.popular': 'Most Popular',
    'pricing.get.started': 'Get Started',
    'pricing.contact.sales': 'Contact Sales',
    'faq.title': 'Frequently Asked Questions',
    'faq.q1': 'How does AI-powered learning work?',
    'faq.a1': 'Our AI analyzes student responses, learning patterns, and performance to create personalized learning experiences that adapt in real-time.',
    'faq.q2': 'Is my data safe and secure?',
    'faq.a2': 'Yes, we use enterprise-grade security measures and comply with educational privacy regulations like FERPA and COPPA.',
    'faq.q3': 'Can I use TeachlyAI offline?',
    'faq.a3': 'While an internet connection is required for AI features, some content can be downloaded for offline study.',
    'faq.q4': 'What age groups is this suitable for?',
    'faq.a4': 'TeachlyAI is designed for students from elementary through high school, with content appropriate for each age group.',
    'faq.q5': 'How do I track my child\'s progress?',
    'faq.a5': 'Parents get access to detailed dashboards showing learning progress, time spent, and areas of strength and improvement.',
    'faq.q6': 'Can teachers integrate this with existing curriculum?',
    'faq.a6': 'Yes, our platform is designed to complement existing curricula and can be customized to match your school\'s requirements.',
    'about.title': 'About TeachlyAI',
    'about.subtitle': 'We\'re on a mission to make quality education accessible to every student, everywhere.',
    'about.vision.title': 'Our Vision',
    'about.vision.desc1': 'We believe that every student deserves personalized attention and the opportunity to learn at their own pace. Our AI-powered platform makes this possible by providing adaptive, engaging, and effective learning experiences.',
    'about.vision.desc2': 'By combining cutting-edge artificial intelligence with proven educational methodologies, we\'re creating the future of learning - one that\'s more inclusive, effective, and inspiring than ever before.',
    'about.impact.title': 'Our Impact',
    'about.impact.desc': 'Transforming education through innovation',
    'about.impact.ai': 'AI-Powered',
    'about.impact.learning': 'Learning',
    'about.impact.global': 'Global',
    'about.impact.accessibility': 'Accessibility',
    'about.impact.adaptive': 'Adaptive',
    'about.impact.curriculum': 'Curriculum',
    'about.impact.realtime': 'Real-time',
    'about.impact.analytics': 'Analytics',
    'contact.title': 'Get in Touch',
    'contact.subtitle': 'Have questions? We\'d love to hear from you.',
    'contact.form.name': 'Name',
    'contact.form.name.placeholder': 'Your name',
    'contact.form.email': 'Email',
    'contact.form.email.placeholder': 'your@email.com',
    'contact.form.message': 'Message',
    'contact.form.message.placeholder': 'Tell us about your needs...',
    'contact.form.send': 'Send Message',
    'final.cta.title': 'Ready to Transform Learning?',
    'final.cta.subtitle': 'Join thousands of students and educators who are already experiencing the future of education.',
    'final.cta.trial': 'Start Free Trial',
    'final.cta.demo': 'Watch Demo'
  },
  es: {
    'auth.title': 'Bienvenido a TeachlyAI',
    'auth.subtitle': 'Únete a miles de estudiantes y educadores transformando el aprendizaje con IA',
    'auth.signInTab': 'Iniciar Sesión',
    'auth.signUpTab': 'Registrarse',
    'auth.email': 'Correo Electrónico',
    'auth.password': 'Contraseña',
    'auth.confirmPassword': 'Confirmar Contraseña',
    'auth.signInButton': 'Iniciar Sesión',
    'auth.signUpButton': 'Registrarse',
    'auth.googleSignIn': 'Continuar con Google',
    'auth.noAccount': '¿No tienes una cuenta?',
    'auth.hasAccount': '¿Ya tienes una cuenta?',
    'auth.signUpLink': 'Regístrate aquí',
    'auth.signInLink': 'Inicia sesión aquí',
    'common.loading': 'Cargando...',
    'chat.title': 'Tutor IA',
    'chat.placeholder': 'Escribe tu mensaje aquí...',
    'chat.send': 'Enviar',
    'chat.newChat': 'Nueva Conversación',
    'chat.previousChats': 'Conversaciones Anteriores',
    'chat.progress': 'Progreso',
    'chat.tokensUsed': 'tokens utilizados',
    'chat.thinking': 'La IA está pensando...',
    'chat.monitoring': 'Monitoreo',
    'hero.title': 'Transforma la Educación con Aprendizaje con IA',
    'hero.subtitle': 'Experiencias de aprendizaje personalizadas y adaptativas que crecen con cada estudiante.',
    'cta.start': 'Comenzar a Aprender',
    'cta.demo': 'Ver Demo',
    'nav.features': 'Características',
    'nav.pricing': 'Precios',
    'nav.about': 'Acerca de',
    'nav.contact': 'Contacto',
    'features.section.title': 'Características Poderosas para la Educación Moderna',
    'features.section.subtitle': 'Nuestra plataforma impulsada por IA se adapta al estilo y ritmo único de aprendizaje de cada estudiante',
    'features.adaptive.title': 'Aprendizaje Adaptativo',
    'features.adaptive.desc': 'Los algoritmos de IA ajustan la dificultad y el contenido basándose en el rendimiento del estudiante.',
    'features.voice.title': 'Interacción por Voz',
    'features.voice.desc': 'Las conversaciones de voz natural hacen que el aprendizaje sea más atractivo y accesible.',
    'features.content.title': 'Contenido Inteligente',
    'features.content.desc': 'Cuestionarios, explicaciones y problemas de práctica generados automáticamente.',
    'features.gamified.title': 'Aprendizaje Gamificado',
    'features.gamified.desc': 'Sistemas de logros, seguimiento de progreso y recompensas mantienen a los estudiantes motivados.',
    'features.analytics.title': 'Análisis en Tiempo Real',
    'features.analytics.desc': 'Información completa sobre el progreso de aprendizaje, fortalezas y áreas de mejora.',
    'features.collaborative.title': 'Herramientas Colaborativas',
    'features.collaborative.desc': 'Conecta estudiantes, maestros y padres con paneles compartidos.'
  },
  fr: {
    'auth.title': 'Bienvenue sur TeachlyAI',
    'auth.subtitle': 'Rejoignez des milliers d\'étudiants et d\'éducateurs transformant l\'apprentissage avec l\'IA',
    'auth.signInTab': 'Se connecter',
    'auth.signUpTab': 'S\'inscrire',
    'auth.email': 'Email',
    'auth.password': 'Mot de passe',
    'auth.confirmPassword': 'Confirmer le mot de passe',
    'auth.signInButton': 'Se connecter',
    'auth.signUpButton': 'S\'inscrire',
    'auth.googleSignIn': 'Continuer avec Google',
    'common.loading': 'Chargement...',
    'hero.title': 'Transformez l\'Éducation avec l\'IA',
    'hero.subtitle': 'Expériences d\'apprentissage personnalisées et adaptatives qui évoluent avec chaque étudiant.',
    'cta.start': 'Commencer l\'Apprentissage',
    'cta.demo': 'Voir la Démo',
    'nav.features': 'Fonctionnalités',
    'nav.pricing': 'Tarifs',
    'nav.about': 'À Propos',
    'nav.contact': 'Contact',
    'features.section.title': 'Fonctionnalités Puissantes pour l\'Éducation Moderne',
    'features.section.subtitle': 'Notre plateforme alimentée par l\'IA s\'adapte au style et au rythme d\'apprentissage unique de chaque étudiant'
  },
  de: {
    'auth.title': 'Willkommen bei TeachlyAI',
    'auth.subtitle': 'Schließen Sie sich Tausenden von Schülern und Pädagogen an, die das Lernen mit KI transformieren',
    'auth.signInTab': 'Anmelden',
    'auth.signUpTab': 'Registrieren',
    'auth.email': 'E-Mail',
    'auth.password': 'Passwort',
    'auth.confirmPassword': 'Passwort bestätigen',
    'auth.signInButton': 'Anmelden',
    'auth.signUpButton': 'Registrieren',
    'auth.googleSignIn': 'Mit Google fortfahren',
    'common.loading': 'Laden...',
    'hero.title': 'Bildung mit KI-gesteuertem Lernen transformieren',
    'hero.subtitle': 'Personalisierte, adaptive Lernerfahrungen, die mit jedem Schüler wachsen.',
    'cta.start': 'Lernen Beginnen',
    'cta.demo': 'Demo Ausprobieren',
    'nav.features': 'Funktionen',
    'nav.pricing': 'Preise',
    'nav.about': 'Über Uns',
    'nav.contact': 'Kontakt'
  },
  zh: {
    'auth.title': '欢迎来到TeachlyAI',
    'auth.subtitle': '加入数千名正在用AI改变学习的学生和教育工作者',
    'auth.signInTab': '登录',
    'auth.signUpTab': '注册',
    'auth.email': '邮箱',
    'auth.password': '密码',
    'auth.confirmPassword': '确认密码',
    'auth.signInButton': '登录',
    'auth.signUpButton': '注册',
    'auth.googleSignIn': '使用Google继续',
    'common.loading': '加载中...',
    'hero.title': '用AI驱动学习改变教育',
    'hero.subtitle': '个性化、适应性学习体验，与每个学生一起成长。',
    'cta.start': '开始学习',
    'cta.demo': '试用演示',
    'nav.features': '功能',
    'nav.pricing': '价格',
    'nav.about': '关于',
    'nav.contact': '联系'
  },
  ja: {
    'auth.title': 'TeachlyAIへようこそ',
    'auth.subtitle': 'AIで学習を変革している何千人もの学生と教育者に参加しましょう',
    'auth.signInTab': 'ログイン',
    'auth.signUpTab': '登録',
    'auth.email': 'メール',
    'auth.password': 'パスワード',
    'auth.confirmPassword': 'パスワード確認',
    'auth.signInButton': 'ログイン',
    'auth.signUpButton': '登録',
    'auth.googleSignIn': 'Googleで続行',
    'common.loading': '読み込み中...',
    'hero.title': 'AIパワード学習で教育を変革',
    'hero.subtitle': '各生徒と共に成長する個別化された適応学習体験。',
    'cta.start': '学習を開始',
    'cta.demo': 'デモを試す',
    'nav.features': '機能',
    'nav.pricing': '料金',
    'nav.about': '概要',
    'nav.contact': 'お問い合わせ'
  },
  pt: {
    'auth.title': 'Bem-vindo ao TeachlyAI',
    'auth.subtitle': 'Junte-se a milhares de estudantes e educadores transformando o aprendizado com IA',
    'auth.signInTab': 'Entrar',
    'auth.signUpTab': 'Registrar',
    'auth.email': 'Email',
    'auth.password': 'Senha',
    'auth.confirmPassword': 'Confirmar Senha',
    'auth.signInButton': 'Entrar',
    'auth.signUpButton': 'Registrar',
    'auth.googleSignIn': 'Continuar com Google',
    'common.loading': 'Carregando...',
    'hero.title': 'Transforme a Educação com Aprendizado Alimentado por IA',
    'hero.subtitle': 'Experiências de aprendizado personalizadas e adaptativas que crescem com cada estudante.',
    'cta.start': 'Começar a Aprender',
    'cta.demo': 'Experimentar Demo',
    'nav.features': 'Recursos',
    'nav.pricing': 'Preços',
    'nav.about': 'Sobre',
    'nav.contact': 'Contato'
  },
  it: {
    'auth.title': 'Benvenuto su TeachlyAI',
    'auth.subtitle': 'Unisciti a migliaia di studenti ed educatori che trasformano l\'apprendimento con l\'IA',
    'auth.signInTab': 'Accedi',
    'auth.signUpTab': 'Registrati',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.confirmPassword': 'Conferma Password',
    'auth.signInButton': 'Accedi',
    'auth.signUpButton': 'Registrati',
    'auth.googleSignIn': 'Continua con Google',
    'common.loading': 'Caricamento...',
    'hero.title': 'Trasforma l\'Educazione con l\'Apprendimento Alimentato dall\'IA',
    'hero.subtitle': 'Esperienze di apprendimento personalizzate e adattive che crescono con ogni studente.',
    'cta.start': 'Inizia ad Imparare',
    'cta.demo': 'Prova la Demo',
    'nav.features': 'Caratteristiche',
    'nav.pricing': 'Prezzi',
    'nav.about': 'Chi Siamo',
    'nav.contact': 'Contatto'
  },
  ru: {
    'auth.title': 'Добро пожаловать в TeachlyAI',
    'auth.subtitle': 'Присоединяйтесь к тысячам студентов и преподавателей, которые трансформируют обучение с помощью ИИ',
    'auth.signInTab': 'Войти',
    'auth.signUpTab': 'Регистрация',
    'auth.email': 'Электронная почта',
    'auth.password': 'Пароль',
    'auth.confirmPassword': 'Подтвердить пароль',
    'auth.signInButton': 'Войти',
    'auth.signUpButton': 'Зарегистрироваться',
    'auth.googleSignIn': 'Продолжить с Google',
    'common.loading': 'Загрузка...',
    'hero.title': 'Трансформируйте образование с помощью ИИ',
    'hero.subtitle': 'Персонализированные, адаптивные учебные опыты, которые растут с каждым студентом.',
    'cta.start': 'Начать Обучение',
    'cta.demo': 'Попробовать Демо',
    'nav.features': 'Возможности',
    'nav.pricing': 'Цены',
    'nav.about': 'О Нас',
    'nav.contact': 'Контакты'
  },
  ar: {
    'auth.title': 'مرحباً بك في TeachlyAI',
    'auth.subtitle': 'انضم إلى آلاف الطلاب والمعلمين الذين يحولون التعلم بالذكاء الاصطناعي',
    'auth.signInTab': 'تسجيل الدخول',
    'auth.signUpTab': 'إنشاء حساب',
    'auth.email': 'البريد الإلكتروني',
    'auth.password': 'كلمة المرور',
    'auth.confirmPassword': 'تأكيد كلمة المرور',
    'auth.signInButton': 'تسجيل الدخول',
    'auth.signUpButton': 'إنشاء حساب',
    'auth.googleSignIn': 'المتابعة مع Google',
    'common.loading': 'جاري التحميل...',
    'hero.title': 'حوّل التعليم بالتعلم المعزز بالذكاء الاصطناعي',
    'hero.subtitle': 'تجارب تعلم شخصية وتكيفية تنمو مع كل طالب.',
    'cta.start': 'ابدأ التعلم',
    'cta.demo': 'جرب العرض التوضيحي',
    'nav.features': 'المميزات',
    'nav.pricing': 'الأسعار',
    'nav.about': 'حول',
    'nav.contact': 'اتصل'
  }
};

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: string): string => {
    const translation = translations[language]?.[key];
    if (!translation) {
      console.warn(`Translation missing for key: ${key} in language: ${language}`);
      return translations['en']?.[key] || key;
    }
    return translation;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
