import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'en' | 'es' | 'fr' | 'de' | 'zh' | 'ja' | 'pt' | 'it' | 'ru' | 'ar';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  en: {
    // Navigation
    'nav.features': 'Features',
    'nav.pricing': 'Pricing',
    'nav.about': 'About',
    'nav.contact': 'Contact',
    'nav.chat': 'Chat',
    'nav.progress': 'Progress',
    'nav.modules': 'Modules',
    
    // Hero Section
    'hero.title': 'Transform Learning with AI-Powered Education',
    'hero.subtitle': 'Experience personalized, interactive education that adapts to every student\'s unique learning style and pace.',
    
    // CTA Buttons
    'cta.start': 'Start Learning',
    'cta.demo': 'Try Demo',
    'cta.trial': 'Start Free Trial',
    
    // Chat
    'chat.title': 'AI Tutor',
    'chat.placeholder': 'Type your message here...',
    'chat.thinking': 'AI is thinking...',
    'chat.tokensUsed': 'tokens used',
    
    'features.section.title': 'Powerful Features for Modern Learning',
    'features.section.subtitle': 'Discover how our AI-powered platform revolutionizes education',
    'features.adaptive.title': 'Adaptive Learning',
    'features.adaptive.desc': 'AI algorithms adjust content difficulty and pacing based on individual student performance and learning patterns.',
    'features.voice.title': 'Voice Interaction',
    'features.voice.desc': 'Natural conversation with AI tutors through voice commands and audio responses for immersive learning.',
    'features.content.title': 'Smart Content',
    'features.content.desc': 'Automatically generated quizzes, exercises, and explanations tailored to each topic and learning objective.',
    'features.gamified.title': 'Gamified Experience',
    'features.gamified.desc': 'Earn points, unlock achievements, and progress through levels to make learning engaging and fun.',
    'features.analytics.title': 'Progress Analytics',
    'features.analytics.desc': 'Detailed insights into learning progress, strengths, and areas for improvement with visual dashboards.',
    'features.collaborative.title': 'Collaborative Learning',
    'features.collaborative.desc': 'Connect with peers, share knowledge, and learn together in virtual study groups and discussions.',
    
    // Features Demo
    'features.demo.title': 'Explore Our',
    'features.demo.subtitle': 'Discover all the powerful tools and features available in our platform',
    'features.demo.allFeatures': 'All Features',
    'features.demo.learning': 'Learning',
    'features.demo.gamification': 'Gamification', 
    'features.demo.tools': 'Tools',
    'features.demo.monitoring': 'Monitoring',
    
    // Subjects
    'subjects.title': 'Comprehensive Subject Coverage',
    'subjects.subtitle': 'Master any subject with our extensive curriculum library',
    'subjects.mathematics.title': 'Mathematics',
    'subjects.mathematics.desc': 'From basic arithmetic to advanced calculus',
    'subjects.sciences.title': 'Sciences',
    'subjects.sciences.desc': 'Biology, Chemistry, Physics, and more',
    'subjects.literature.title': 'Literature',
    'subjects.literature.desc': 'Language arts and reading comprehension',
    'subjects.social.title': 'Social Studies',
    'subjects.social.desc': 'History, geography, and civics',
    'subjects.technology.title': 'Technology',
    'subjects.technology.desc': 'Programming and digital literacy',
    'subjects.arts.title': 'Arts',
    'subjects.arts.desc': 'Creative expression and design',
    'subjects.languages.title': 'Languages',
    'subjects.languages.desc': 'Multiple language learning support',
    'subjects.health.title': 'Health & PE',
    'subjects.health.desc': 'Physical education and wellness',
    
    // Advanced Features
    'advanced.title': 'Advanced Learning Capabilities',
    'advanced.adaptive.title': 'Personalized Learning Paths',
    'advanced.adaptive.desc': 'Every student gets a unique learning journey tailored to their goals, interests, and learning style.',
    'advanced.feedback.title': 'Instant Feedback',
    'advanced.feedback.desc': 'Get immediate, constructive feedback on assignments and questions to accelerate your learning.',
    'advanced.safe.title': 'Safe Learning Environment',
    'advanced.safe.desc': 'Secure, monitored platform with age-appropriate content and parental controls.',
    'advanced.availability.title': '24/7 Availability',
    'advanced.availability.desc': 'Learn anytime, anywhere with our always-available AI tutors and learning resources.',
    
    // Achievement
    'achievement.title': 'Track Your Progress',
    'achievement.desc': 'Monitor your learning journey with detailed analytics and achievements',
    'achievement.streak': 'Learning Streak',
    'achievement.progress': 'Building',
    'achievement.problems': 'Problems Solved',
    'achievement.tracking': 'Tracking',
    'achievement.level': 'Current Level',
    'achievement.growing': 'Growing',
    
    // Testimonials
    'testimonials.title': 'What Our Users Say',
    'testimonials.subtitle': 'Hear from educators, students, and parents',
    'testimonials.teacher': 'High School Teacher',
    'testimonials.teacher.content': 'This platform has transformed how I teach. Students are more engaged and learning outcomes have improved significantly.',
    'testimonials.parent': 'Parent of 3',
    'testimonials.parent.content': 'My children love learning with the AI tutor. It\'s like having a personal teacher available 24/7.',
    'testimonials.principal': 'School Principal',
    'testimonials.principal.content': 'We\'ve seen remarkable improvements in student performance since implementing this AI-powered learning system.',
    
    // Pricing
    'pricing.title': 'Choose Your Learning Plan',
    'pricing.subtitle': 'Flexible pricing for every learning need',
    'pricing.individual': 'Individual',
    'pricing.individual.price': '$19',
    'pricing.individual.feature1': 'AI Tutor Access',
    'pricing.individual.feature2': 'Progress Tracking',
    'pricing.individual.feature3': 'Voice Interaction',
    'pricing.individual.feature4': 'Basic Analytics',
    'pricing.family': 'Family',
    'pricing.family.price': '$39',
    'pricing.family.feature1': 'Up to 5 Students',
    'pricing.family.feature2': 'Parental Dashboard',
    'pricing.family.feature3': 'Advanced Analytics',
    'pricing.family.feature4': 'Priority Support',
    'pricing.school': 'School',
    'pricing.school.price': 'Custom',
    'pricing.school.feature1': 'Unlimited Students',
    'pricing.school.feature2': 'Admin Dashboard',
    'pricing.school.feature3': 'Custom Curriculum',
    'pricing.school.feature4': 'Dedicated Support',
    'pricing.month': '/month',
    'pricing.most.popular': 'Most Popular',
    'pricing.get.started': 'Get Started',
    'pricing.contact.sales': 'Contact Sales',
    
    // FAQ
    'faq.title': 'Frequently Asked Questions',
    'faq.q1': 'How does the AI tutor work?',
    'faq.a1': 'Our AI tutor uses advanced natural language processing to understand student questions and provide personalized explanations, adapting to each student\'s learning style.',
    'faq.q2': 'Is the platform safe for children?',
    'faq.a2': 'Yes, we prioritize safety with age-appropriate content, parental controls, and secure data handling. All interactions are monitored for safety.',
    'faq.q3': 'What subjects are covered?',
    'faq.a3': 'We cover all major subjects including Mathematics, Sciences, Literature, Social Studies, Languages, and more, aligned with curriculum standards.',
    'faq.q4': 'Can parents track their child\'s progress?',
    'faq.a4': 'Yes, parents have access to detailed progress reports, learning analytics, and can set learning goals for their children.',
    'faq.q5': 'How much does it cost?',
    'faq.a5': 'We offer flexible pricing starting at $19/month for individuals, with family and school plans available. Try our free demo first!',
    'faq.q6': 'Is there customer support?',
    'faq.a6': 'Yes, we provide 24/7 customer support through chat, email, and phone. Premium users get priority support.',
    
    // About
    'about.title': 'About Our Mission',
    'about.subtitle': 'Revolutionizing education through artificial intelligence',
    'about.vision.title': 'Our Vision',
    'about.vision.desc1': 'We believe every student deserves access to personalized, high-quality education. Our AI-powered platform makes this possible by adapting to individual learning styles and providing instant, intelligent feedback.',
    'about.vision.desc2': 'By combining cutting-edge AI technology with proven educational methodologies, we\'re creating a future where learning is more effective, engaging, and accessible to everyone.',
    'about.impact.title': 'Our Impact',
    'about.impact.desc': 'See how we\'re transforming education worldwide',
    'about.impact.ai': 'AI-Powered',
    'about.impact.learning': 'Learning',
    'about.impact.global': 'Global',
    'about.impact.accessibility': 'Accessibility',
    'about.impact.adaptive': 'Adaptive',
    'about.impact.curriculum': 'Curriculum',
    'about.impact.realtime': 'Real-time',
    'about.impact.analytics': 'Analytics',
    
    // Contact
    'contact.title': 'Get in Touch',
    'contact.subtitle': 'Ready to transform your learning experience?',
    'contact.form.name': 'Name',
    'contact.form.name.placeholder': 'Your Name',
    'contact.form.email': 'Email',
    'contact.form.email.placeholder': 'your@email.com',
    'contact.form.message': 'Message',
    'contact.form.message.placeholder': 'Tell us about your learning goals...',
    'contact.form.send': 'Send Message',
    
    // Final CTA
    'final.cta.title': 'Ready to Start Your Learning Journey?',
    'final.cta.subtitle': 'Join thousands of students already transforming their education with AI-powered learning.',
    'final.cta.demo': 'Try Demo',
    
    // Modules
    'modules.title': 'Learning Modules',
    'modules.description': 'Explore our comprehensive curriculum modules',
    'modules.searchPlaceholder': 'Search modules...',
    'modules.subjects': 'Subjects',
    'modules.standards': 'Standards',
    'modules.startLearning': 'Start Learning',
    'modules.noModulesFound': 'No modules found',
    'modules.adjustFilters': 'Try adjusting your search or filters',
    'modules.categories.all': 'All Subjects',
    'modules.categories.math': 'Mathematics',
    'modules.categories.science': 'Science',
    'modules.categories.english': 'English',
    'modules.categories.history': 'History',
    
    // Common
    'common.back': 'Back',
    'common.more': 'more',
  },
  es: {
    'nav.features': 'Características',
    'nav.pricing': 'Precios',
    'nav.about': 'Acerca de',
    'nav.contact': 'Contacto',
    'nav.chat': 'Chat',
    'nav.progress': 'Progreso',
    'nav.modules': 'Módulos',
    'hero.title': 'Transforma el Aprendizaje con Educación Impulsada por IA',
    'hero.subtitle': 'Experimenta educación personalizada e interactiva que se adapta al estilo y ritmo de aprendizaje único de cada estudiante.',
    'cta.start': 'Comenzar a Aprender',
    'cta.demo': 'Probar Demo',
    'cta.trial': 'Comenzar Prueba Gratuita',
    'chat.title': 'Tutor IA',
    'chat.placeholder': 'Escribe tu mensaje aquí...',
    'chat.thinking': 'La IA está pensando...',
    'chat.tokensUsed': 'tokens utilizados',
    'features.section.title': 'Características Poderosas para el Aprendizaje Moderno',
    'features.section.subtitle': 'Descubre cómo nuestra plataforma impulsada por IA revoluciona la educación',
    'features.adaptive.title': 'Aprendizaje Adaptativo',
    'features.adaptive.desc': 'Los algoritmos de IA ajustan la dificultad y el ritmo del contenido basándose en el rendimiento individual del estudiante y los patrones de aprendizaje.',
    'features.voice.title': 'Interacción por Voz',
    'features.voice.desc': 'Conversación natural con tutores de IA a través de comandos de voz y respuestas de audio para un aprendizaje inmersivo.',
    'features.content.title': 'Contenido Inteligente',
    'features.content.desc': 'Cuestionarios, ejercicios y explicaciones generados automáticamente adaptados a cada tema y objetivo de aprendizaje.',
    'features.gamified.title': 'Experiencia Gamificada',
    'features.gamified.desc': 'Gana puntos, desbloquea logros y progresa a través de niveles para hacer el aprendizaje atractivo y divertido.',
    'features.analytics.title': 'Análisis de Progreso',
    'features.analytics.desc': 'Información detallada sobre el progreso de aprendizaje, fortalezas y áreas de mejora con paneles visuales.',
    'features.collaborative.title': 'Aprendizaje Colaborativo',
    'features.collaborative.desc': 'Conéctate con compañeros, comparte conocimiento y aprende juntos en grupos de estudio virtuales y discusiones.',
    'features.demo.title': 'Explora Nuestras',
    'features.demo.subtitle': 'Descubre todas las herramientas y características poderosas disponibles en nuestra plataforma',
    'features.demo.allFeatures': 'Todas las Características',
    'features.demo.learning': 'Aprendizaje',
    'features.demo.gamification': 'Gamificación',
    'features.demo.tools': 'Herramientas',
    'features.demo.monitoring': 'Monitoreo',
    'subjects.title': 'Cobertura Integral de Materias',
    'subjects.subtitle': 'Domina cualquier materia con nuestra amplia biblioteca de currículos',
    'testimonials.title': 'Lo que Dicen Nuestros Usuarios',
    'testimonials.subtitle': 'Escucha a educadores, estudiantes y padres',
    'pricing.title': 'Elige tu Plan de Aprendizaje',
    'pricing.subtitle': 'Precios flexibles para cada necesidad de aprendizaje',
    'faq.title': 'Preguntas Frecuentes',
    'about.title': 'Sobre Nuestra Misión',
    'about.subtitle': 'Revolucionando la educación a través de la inteligencia artificial',
    'contact.title': 'Ponte en Contacto',
    'contact.subtitle': '¿Listo para transformar tu experiencia de aprendizaje?',
    'modules.title': 'Módulos de Aprendizaje',
    'modules.description': 'Explora nuestros módulos de currículo integral',
    'common.back': 'Atrás',
    'common.more': 'más',
  },
  fr: {
    'nav.features': 'Fonctionnalités',
    'nav.pricing': 'Tarifs',
    'nav.about': 'À propos',
    'nav.contact': 'Contact',
    'nav.chat': 'Chat',
    'nav.progress': 'Progrès',
    'nav.modules': 'Modules',
    'hero.title': 'Transformez l\'Apprentissage avec l\'Éducation Alimentée par l\'IA',
    'hero.subtitle': 'Découvrez une éducation personnalisée et interactive qui s\'adapte au style et au rythme d\'apprentissage unique de chaque étudiant.',
    'cta.start': 'Commencer à Apprendre',
    'cta.demo': 'Essayer la Démo',
    'cta.trial': 'Commencer l\'Essai Gratuit',
    'chat.title': 'Tuteur IA',
    'chat.placeholder': 'Tapez votre message ici...',
    'chat.thinking': 'L\'IA réfléchit...',
    'chat.tokensUsed': 'jetons utilisés',
    'features.demo.title': 'Explorez Nos',
    'features.demo.subtitle': 'Découvrez tous les outils et fonctionnalités puissants disponibles dans notre plateforme',
    'features.demo.allFeatures': 'Toutes les Fonctionnalités',
    'features.demo.learning': 'Apprentissage',
    'features.demo.gamification': 'Ludification',
    'features.demo.tools': 'Outils',
    'features.demo.monitoring': 'Surveillance',
    'features.section.title': 'Fonctionnalités Puissantes pour l\'Apprentissage Moderne',
    'subjects.title': 'Couverture Complète des Matières',
    'testimonials.title': 'Ce que Disent Nos Utilisateurs',
    'pricing.title': 'Choisissez Votre Plan d\'Apprentissage',
    'faq.title': 'Questions Fréquemment Posées',
    'about.title': 'À Propos de Notre Mission',
    'contact.title': 'Contactez-Nous',
    'modules.title': 'Modules d\'Apprentissage',
    'common.back': 'Retour',
    'common.more': 'plus',
  },
  de: {
    'nav.features': 'Funktionen',
    'nav.pricing': 'Preise',
    'nav.about': 'Über uns',
    'nav.contact': 'Kontakt',
    'nav.chat': 'Chat',
    'nav.progress': 'Fortschritt',
    'nav.modules': 'Module',
    'hero.title': 'Transformieren Sie das Lernen mit KI-gestützter Bildung',
    'hero.subtitle': 'Erleben Sie personalisierte, interaktive Bildung, die sich an jeden individuellen Lernstil und jedes Tempo anpasst.',
    'cta.start': 'Lernen Beginnen',
    'cta.demo': 'Demo Ausprobieren',
    'cta.trial': 'Kostenlose Testversion Starten',
    'chat.title': 'KI-Tutor',
    'chat.placeholder': 'Geben Sie Ihre Nachricht hier ein...',
    'chat.thinking': 'KI denkt nach...',
    'chat.tokensUsed': 'verwendete Token',
    'features.demo.title': 'Entdecken Sie Unsere',
    'features.demo.subtitle': 'Entdecken Sie alle leistungsstarken Tools und Funktionen in unserer Plattform',
    'features.demo.allFeatures': 'Alle Funktionen',
    'features.demo.learning': 'Lernen',
    'features.demo.gamification': 'Gamification',
    'features.demo.tools': 'Werkzeuge',
    'features.demo.monitoring': 'Überwachung',
    'features.section.title': 'Leistungsstarke Funktionen für Modernes Lernen',
    'subjects.title': 'Umfassende Fächerabdeckung',
    'testimonials.title': 'Was Unsere Benutzer Sagen',
    'pricing.title': 'Wählen Sie Ihren Lernplan',
    'faq.title': 'Häufig Gestellte Fragen',
    'about.title': 'Über Unsere Mission',
    'contact.title': 'Kontakt Aufnehmen',
    'modules.title': 'Lernmodule',
    'common.back': 'Zurück',
    'common.more': 'mehr',
  },
  zh: {
    'nav.features': '功能',
    'nav.pricing': '价格',
    'nav.about': '关于',
    'nav.contact': '联系',
    'nav.chat': '聊天',
    'nav.progress': '进度',
    'nav.modules': '模块',
    'hero.title': '用AI驱动的教育改变学习',
    'hero.subtitle': '体验个性化的互动教育，适应每个学生独特的学习风格和节奏。',
    'cta.start': '开始学习',
    'cta.demo': '试用演示',
    'cta.trial': '开始免费试用',
    'chat.title': 'AI导师',
    'chat.placeholder': '在这里输入您的信息...',
    'chat.thinking': 'AI正在思考...',
    'chat.tokensUsed': '已使用的令牌',
    'features.demo.title': '探索我们的',
    'features.demo.subtitle': '发现我们平台中所有强大的工具和功能',
    'features.demo.allFeatures': '所有功能',
    'features.demo.learning': '学习',
    'features.demo.gamification': '游戏化',
    'features.demo.tools': '工具',
    'features.demo.monitoring': '监控',
    'features.section.title': '现代学习的强大功能',
    'subjects.title': '全面的学科覆盖',
    'testimonials.title': '用户评价',
    'pricing.title': '选择您的学习计划',
    'faq.title': '常见问题',
    'about.title': '关于我们的使命',
    'contact.title': '联系我们',
    'modules.title': '学习模块',
    'common.back': '返回',
    'common.more': '更多',
  },
  ja: {
    'nav.features': '機能',
    'nav.pricing': '価格',
    'nav.about': '概要',
    'nav.contact': 'お問い合わせ',
    'nav.chat': 'チャット',
    'nav.progress': '進捗',
    'nav.modules': 'モジュール',
    'hero.title': 'AI駆動教育で学習を変革',
    'hero.subtitle': '各学生のユニークな学習スタイルとペースに適応する、パーソナライズされたインタラクティブな教育を体験してください。',
    'cta.start': '学習を始める',
    'cta.demo': 'デモを試す',
    'cta.trial': '無料トライアルを開始',
    'chat.title': 'AIチューター',
    'chat.placeholder': 'ここにメッセージを入力してください...',
    'chat.thinking': 'AIが考えています...',
    'chat.tokensUsed': '使用されたトークン',
    'features.demo.title': '私たちの機能を',
    'features.demo.subtitle': 'プラットフォームで利用可能なすべての強力なツールと機能を発見してください',
    'features.demo.allFeatures': 'すべての機能',
    'features.demo.learning': '学習',
    'features.demo.gamification': 'ゲーミフィケーション',
    'features.demo.tools': 'ツール',
    'features.demo.monitoring': 'モニタリング',
    'features.section.title': '現代学習のための強力な機能',
    'subjects.title': '包括的な科目カバレッジ',
    'testimonials.title': 'ユーザーの声',
    'pricing.title': '学習プランを選択',
    'faq.title': 'よくある質問',
    'about.title': '私たちの使命について',
    'contact.title': 'お問い合わせ',
    'modules.title': '学習モジュール',
    'common.back': '戻る',
    'common.more': 'もっと',
  },
  pt: {
    'nav.features': 'Recursos',
    'nav.pricing': 'Preços',
    'nav.about': 'Sobre',
    'nav.contact': 'Contato',
    'nav.chat': 'Chat',
    'nav.progress': 'Progresso',
    'nav.modules': 'Módulos',
    'hero.title': 'Transforme o Aprendizado com Educação Impulsionada por IA',
    'hero.subtitle': 'Experimente educação personalizada e interativa que se adapta ao estilo e ritmo de aprendizado único de cada estudante.',
    'cta.start': 'Começar a Aprender',
    'cta.demo': 'Experimentar Demo',
    'cta.trial': 'Iniciar Teste Gratuito',
    'chat.title': 'Tutor IA',
    'chat.placeholder': 'Digite sua mensagem aqui...',
    'chat.thinking': 'IA está pensando...',
    'chat.tokensUsed': 'tokens usados',
    'features.demo.title': 'Explore Nossos',
    'features.demo.subtitle': 'Descubra todas as ferramentas e recursos poderosos disponíveis em nossa plataforma',
    'features.demo.allFeatures': 'Todos os Recursos',
    'features.demo.learning': 'Aprendizado',
    'features.demo.gamification': 'Gamificação',
    'features.demo.tools': 'Ferramentas',
    'features.demo.monitoring': 'Monitoramento',
    'features.section.title': 'Recursos Poderosos para Aprendizado Moderno',
    'subjects.title': 'Cobertura Abrangente de Matérias',
    'testimonials.title': 'O que Nossos Usuários Dizem',
    'pricing.title': 'Escolha Seu Plano de Aprendizado',
    'faq.title': 'Perguntas Frequentes',
    'about.title': 'Sobre Nossa Missão',
    'contact.title': 'Entre em Contato',
    'modules.title': 'Módulos de Aprendizado',
    'common.back': 'Voltar',
    'common.more': 'mais',
  },
  it: {
    'nav.features': 'Funzionalità',
    'nav.pricing': 'Prezzi',
    'nav.about': 'Chi siamo',
    'nav.contact': 'Contatto',
    'nav.chat': 'Chat',
    'nav.progress': 'Progresso',
    'nav.modules': 'Moduli',
    'hero.title': 'Trasforma l\'Apprendimento con l\'Educazione Potenziata dall\'IA',
    'hero.subtitle': 'Sperimenta un\'educazione personalizzata e interattiva che si adatta allo stile e al ritmo di apprendimento unico di ogni studente.',
    'cta.start': 'Inizia ad Imparare',
    'cta.demo': 'Prova la Demo',
    'cta.trial': 'Inizia la Prova Gratuita',
    'chat.title': 'Tutor IA',
    'chat.placeholder': 'Scrivi il tuo messaggio qui...',
    'chat.thinking': 'L\'IA sta pensando...',
    'chat.tokensUsed': 'token utilizzati',
    'features.demo.title': 'Esplora le Nostre',
    'features.demo.subtitle': 'Scopri tutti gli strumenti e le funzionalità potenti disponibili nella nostra piattaforma',
    'features.demo.allFeatures': 'Tutte le Funzionalità',
    'features.demo.learning': 'Apprendimento',
    'features.demo.gamification': 'Gamification',
    'features.demo.tools': 'Strumenti',
    'features.demo.monitoring': 'Monitoraggio',
    'features.section.title': 'Funzionalità Potenti per l\'Apprendimento Moderno',
    'subjects.title': 'Copertura Completa delle Materie',
    'testimonials.title': 'Cosa Dicono i Nostri Utenti',
    'pricing.title': 'Scegli il Tuo Piano di Apprendimento',
    'faq.title': 'Domande Frequenti',
    'about.title': 'Sulla Nostra Missione',
    'contact.title': 'Contattaci',
    'modules.title': 'Moduli di Apprendimento',
    'common.back': 'Indietro',
    'common.more': 'di più',
  },
  ru: {
    'nav.features': 'Возможности',
    'nav.pricing': 'Цены',
    'nav.about': 'О нас',
    'nav.contact': 'Контакты',
    'nav.chat': 'Чат',
    'nav.progress': 'Прогресс',
    'nav.modules': 'Модули',
    'hero.title': 'Преобразуйте Обучение с Образованием на Основе ИИ',
    'hero.subtitle': 'Испытайте персонализированное, интерактивное образование, которое адаптируется к уникальному стилю и темпу обучения каждого студента.',
    'cta.start': 'Начать Обучение',
    'cta.demo': 'Попробовать Демо',
    'cta.trial': 'Начать Бесплатную Пробную Версию',
    'chat.title': 'ИИ Репетитор',
    'chat.placeholder': 'Введите ваше сообщение здесь...',
    'chat.thinking': 'ИИ думает...',
    'chat.tokensUsed': 'использованные токены',
    'features.demo.title': 'Исследуйте Наши',
    'features.demo.subtitle': 'Откройте для себя все мощные инструменты и функции, доступные на нашей платформе',
    'features.demo.allFeatures': 'Все Функции',
    'features.demo.learning': 'Обучение',
    'features.demo.gamification': 'Геймификация',
    'features.demo.tools': 'Инструменты',
    'features.demo.monitoring': 'Мониторинг',
    'features.section.title': 'Мощные Функции для Современного Обучения',
    'subjects.title': 'Всестороннее Покрытие Предметов',
    'testimonials.title': 'Что Говорят Наши Пользователи',
    'pricing.title': 'Выберите Ваш План Обучения',
    'faq.title': 'Часто Задаваемые Вопросы',
    'about.title': 'О Нашей Миссии',
    'contact.title': 'Связаться с Нами',
    'modules.title': 'Модули Обучения',
    'common.back': 'Назад',
    'common.more': 'больше',
  },
  ar: {
    'nav.features': 'الميزات',
    'nav.pricing': 'الأسعار',
    'nav.about': 'حولنا',
    'nav.contact': 'اتصل بنا',
    'nav.chat': 'الدردشة',
    'nav.progress': 'التقدم',
    'nav.modules': 'الوحدات',
    'hero.title': 'حوّل التعلم بالتعليم المدعوم بالذكاء الاصطناعي',
    'hero.subtitle': 'اختبر تعليماً شخصياً وتفاعلياً يتكيف مع أسلوب ووتيرة التعلم الفريدة لكل طالب.',
    'cta.start': 'ابدأ التعلم',
    'cta.demo': 'جرب العرض التوضيحي',
    'cta.trial': 'ابدأ التجربة المجانية',
    'chat.title': 'مدرس الذكاء الاصطناعي',
    'chat.placeholder': 'اكتب رسالتك هنا...',
    'chat.thinking': 'الذكاء الاصطناعي يفكر...',
    'chat.tokensUsed': 'الرموز المستخدمة',
    'features.demo.title': 'استكشف',
    'features.demo.subtitle': 'اكتشف جميع الأدوات والميزات القوية المتاحة في منصتنا',
    'features.demo.allFeatures': 'جميع الميزات',
    'features.demo.learning': 'التعلم',
    'features.demo.gamification': 'اللعب',
    'features.demo.tools': 'الأدوات',
    'features.demo.monitoring': 'المراقبة',
    'features.section.title': 'ميزات قوية للتعلم الحديث',
    'subjects.title': 'تغطية شاملة للمواد',
    'testimonials.title': 'ما يقوله مستخدمونا',
    'pricing.title': 'اختر خطة التعلم الخاصة بك',
    'faq.title': 'الأسئلة الشائعة',
    'about.title': 'حول مهمتنا',
    'contact.title': 'تواصل معنا',
    'modules.title': 'وحدات التعلم',
    'common.back': 'العودة',
    'common.more': 'المزيد',
  },
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('en');

  useEffect(() => {
    const savedLanguage = localStorage.getItem('language') as Language;
    if (savedLanguage && translations[savedLanguage]) {
      setLanguage(savedLanguage);
    }
  }, []);

  const changeLanguage = (lang: Language) => {
    setLanguage(lang);
    localStorage.setItem('language', lang);
  };

  const t = (key: string): string => {
    const currentTranslations = translations[language];
    const englishTranslations = translations['en'];
    
    // Return the translation if it exists, otherwise fallback to English, otherwise return the key
    return currentTranslations?.[key] || englishTranslations?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage: changeLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
