import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'en' | 'es' | 'fr' | 'de' | 'zh' | 'ja' | 'pt' | 'it' | 'ru' | 'ar';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  en: {
    // Navigation
    'nav.features': 'Features',
    'nav.pricing': 'Pricing',
    'nav.about': 'About',
    'nav.contact': 'Contact',
    'nav.login': 'Login',
    'nav.signup': 'Sign Up',
    'nav.dashboard': 'Dashboard',
    'nav.logout': 'Logout',

    // Hero Section
    'hero.title': 'The Future of AI-Powered Learning is Here',
    'hero.subtitle': 'Experience personalized education with our advanced AI tutor that adapts to your learning style, provides instant feedback, and makes learning engaging through gamification.',

    // CTA
    'cta.start': 'Start Learning Now',
    'cta.demo': 'Try Demo',
    'cta.trial': 'Start Free Trial',

    // Features Section
    'features.section.title': 'Powerful Features for Modern Learning',
    'features.section.subtitle': 'Discover how our AI-powered platform transforms education through personalized learning experiences.',
    'features.adaptive.title': 'Adaptive AI Learning',
    'features.adaptive.desc': 'Our AI adapts to your learning pace and style, providing personalized content and difficulty levels.',
    'features.voice.title': 'Voice Conversations',
    'features.voice.desc': 'Practice speaking and listening with natural voice interactions powered by advanced AI.',
    'features.content.title': 'Dynamic Content Generation',
    'features.content.desc': 'Get unlimited practice problems, explanations, and learning materials generated in real-time.',
    'features.gamified.title': 'Gamified Learning',
    'features.gamified.desc': 'Stay motivated with achievements, levels, and rewards that make learning fun and engaging.',
    'features.analytics.title': 'Advanced Analytics',
    'features.analytics.desc': 'Track your progress with detailed insights and personalized learning recommendations.',
    'features.collaborative.title': 'Collaborative Learning',
    'features.collaborative.desc': 'Connect with peers and teachers in a safe, moderated learning environment.',

    // Subjects
    'subjects.title': 'Comprehensive Subject Coverage',
    'subjects.subtitle': 'Master any subject with our AI-powered tutoring across all academic disciplines.',
    'subjects.mathematics.title': 'Mathematics',
    'subjects.mathematics.desc': 'From basic arithmetic to advanced calculus',
    'subjects.sciences.title': 'Sciences',
    'subjects.sciences.desc': 'Physics, Chemistry, Biology, and more',
    'subjects.literature.title': 'Literature',
    'subjects.literature.desc': 'Reading comprehension and writing skills',
    'subjects.social.title': 'Social Studies',
    'subjects.social.desc': 'History, Geography, and Civics',
    'subjects.technology.title': 'Technology',
    'subjects.technology.desc': 'Programming and digital literacy',
    'subjects.arts.title': 'Arts',
    'subjects.arts.desc': 'Creative expression and art history',
    'subjects.languages.title': 'Languages',
    'subjects.languages.desc': 'Learn new languages with AI conversation',
    'subjects.health.title': 'Health & PE',
    'subjects.health.desc': 'Physical and mental wellness education',

    // Advanced Features
    'advanced.title': 'Advanced Learning Features',
    'advanced.adaptive.title': 'Smart Difficulty Adjustment',
    'advanced.adaptive.desc': 'Our AI continuously adjusts the difficulty based on your performance and learning patterns.',
    'advanced.feedback.title': 'Instant Feedback',
    'advanced.feedback.desc': 'Get immediate explanations and corrections to accelerate your learning process.',
    'advanced.safe.title': 'Safe Learning Environment',
    'advanced.safe.desc': 'Protected, monitored environment designed specifically for educational interactions.',
    'advanced.availability.title': '24/7 Availability',
    'advanced.availability.desc': 'Learn anytime, anywhere with our always-available AI tutor.',

    // Achievement
    'achievement.title': 'Track Your Progress',
    'achievement.desc': 'See how you\'re improving with detailed analytics and achievements.',
    'achievement.streak': 'Learning Streak',
    'achievement.progress': '12 Days',
    'achievement.problems': 'Problems Solved',
    'achievement.tracking': '247 Total',
    'achievement.level': 'Current Level',
    'achievement.growing': 'Level 8',

    // Testimonials
    'testimonials.title': 'What Our Users Say',
    'testimonials.subtitle': 'Join thousands of satisfied learners worldwide',
    'testimonials.teacher': 'High School Teacher',
    'testimonials.teacher.content': 'TeachlyAI has revolutionized how I teach. My students are more engaged and their test scores have improved dramatically.',
    'testimonials.parent': 'Parent of Middle Schooler',
    'testimonials.parent.content': 'My daughter actually looks forward to studying now. The gamification features keep her motivated and learning.',
    'testimonials.principal': 'School Principal',
    'testimonials.principal.content': 'We\'ve seen a 40% improvement in student engagement since implementing TeachlyAI across our curriculum.',

    // Pricing
    'pricing.title': 'Choose Your Learning Plan',
    'pricing.subtitle': 'Flexible pricing for students, families, and schools',
    'pricing.individual': 'Individual',
    'pricing.individual.price': '$9.99',
    'pricing.family': 'Family',
    'pricing.family.price': '$19.99',
    'pricing.school': 'School',
    'pricing.school.price': 'Custom',
    'pricing.month': '/month',
    'pricing.most.popular': 'Most Popular',
    'pricing.get.started': 'Get Started',
    'pricing.contact.sales': 'Contact Sales',
    'pricing.individual.feature1': 'Personal AI tutor',
    'pricing.individual.feature2': 'All subjects covered',
    'pricing.individual.feature3': 'Progress tracking',
    'pricing.individual.feature4': 'Mobile app access',
    'pricing.family.feature1': 'Up to 5 students',
    'pricing.family.feature2': 'Parent dashboard',
    'pricing.family.feature3': 'Family progress reports',
    'pricing.family.feature4': 'Priority support',
    'pricing.school.feature1': 'Unlimited students',
    'pricing.school.feature2': 'Teacher dashboard',
    'pricing.school.feature3': 'Advanced analytics',
    'pricing.school.feature4': 'Custom integration',

    // FAQ
    'faq.title': 'Frequently Asked Questions',
    'faq.q1': 'How does the AI adapt to different learning styles?',
    'faq.a1': 'Our AI analyzes your responses, learning pace, and preferences to customize content delivery, difficulty levels, and teaching methods that work best for you.',
    'faq.q2': 'Is TeachlyAI suitable for all age groups?',
    'faq.a2': 'Yes! Our platform adapts to learners from elementary school through college and beyond, with age-appropriate content and interfaces.',
    'faq.q3': 'How do I track my child\'s progress?',
    'faq.a3': 'Parents get access to detailed dashboards showing learning time, subjects studied, achievements earned, and areas that need attention.',
    'faq.q4': 'Can TeachlyAI help with homework and test preparation?',
    'faq.a4': 'Absolutely! Our AI can help explain concepts, solve problems step-by-step, and create practice tests tailored to your curriculum.',
    'faq.q5': 'Is my data safe and private?',
    'faq.a5': 'We take privacy seriously. All data is encrypted, and we never share personal information. We comply with COPPA, FERPA, and GDPR regulations.',
    'faq.q6': 'What subjects does TeachlyAI cover?',
    'faq.a6': 'We cover all major subjects including Math, Science, English, History, Foreign Languages, and more, with new subjects added regularly.',

    // About
    'about.title': 'About TeachlyAI',
    'about.subtitle': 'We\'re on a mission to democratize quality education through AI technology.',
    'about.vision.title': 'Our Vision',
    'about.vision.desc1': 'We believe every student deserves access to personalized, high-quality education. Our AI-powered platform breaks down barriers and makes learning accessible to everyone, everywhere.',
    'about.vision.desc2': 'By combining cutting-edge AI with proven educational methodologies, we create engaging learning experiences that adapt to each student\'s unique needs and learning style.',
    'about.impact.title': 'Our Impact',
    'about.impact.desc': 'TeachlyAI is transforming education with innovative features:',
    'about.impact.ai': 'AI-Powered',
    'about.impact.learning': 'Personalized Learning',
    'about.impact.global': '24/7',
    'about.impact.accessibility': 'Global Accessibility',
    'about.impact.adaptive': 'Adaptive',
    'about.impact.curriculum': 'Smart Curriculum',
    'about.impact.realtime': 'Real-time',
    'about.impact.analytics': 'Progress Analytics',

    // Contact
    'contact.title': 'Get in Touch',
    'contact.subtitle': 'Have questions? We\'d love to hear from you.',
    'contact.form.name': 'Full Name',
    'contact.form.name.placeholder': 'Enter your full name',
    'contact.form.email': 'Email Address',
    'contact.form.email.placeholder': 'Enter your email address',
    'contact.form.message': 'Message',
    'contact.form.message.placeholder': 'Tell us how we can help you',
    'contact.form.send': 'Send Message',

    // Final CTA
    'final.cta.title': 'Ready to Transform Your Learning?',
    'final.cta.subtitle': 'Join millions of students already learning smarter with TeachlyAI.',
    'final.cta.demo': 'Watch Demo',

    // Chat
    'chat.navigation.chat': 'Chat',
    'chat.navigation.progress': 'Progress',
    'chat.navigation.modules': 'Modules',
    'chat.title': 'AI Learning Chat',
    'chat.subtitle': 'Ask me anything about your studies!',
    'chat.placeholder': 'Type your question here...',
    'chat.send': 'Send',
    'chat.voice': 'Voice Chat',
    'chat.clear': 'Clear Chat',

    // Progress
    'progress.title': 'Learning Progress',
    'progress.description': 'Track your learning journey and achievements',
    'progress.demoTitle': 'Demo Learning Progress',
    'progress.demoDescription': 'This is a demo showing what your progress dashboard would look like',
    'progress.demoNotice': 'This is demo data. Sign up to track your real progress!',
    'progress.notAvailable': 'Progress tracking not available for your account type.',
    'progress.tabs.monitoring': 'Overview',
    'progress.tabs.childProgress': 'Child Progress',
    'progress.tabs.quests': 'Quests',
    'progress.tabs.achievements': 'Achievements',
    'progress.tabs.subjects': 'Subjects',
    'progress.tabs.analytics': 'Analytics',

    // Modules
    'modules.title': 'Learning Modules',
    'modules.description': 'Explore structured learning paths across different subjects',
    'modules.demoTitle': 'Demo Learning Modules',
    'modules.demoDescription': 'This shows the available learning modules in our platform',
    'modules.demoNotice': 'This is demo content. Sign up to access full learning modules!',
    'modules.coming.soon': 'More modules coming soon!',

    // Testing
    'testing.title': 'Testing',
    'testing.createTest': 'Create Custom Test',
    'testing.quizLibrary': 'Quiz Library',

    // Auth
    'auth.login.title': 'Welcome Back',
    'auth.login.subtitle': 'Sign in to continue your learning journey',
    'auth.signup.title': 'Join TeachlyAI',
    'auth.signup.subtitle': 'Start your personalized learning experience',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.confirmPassword': 'Confirm Password',
    'auth.login.button': 'Sign In',
    'auth.signup.button': 'Create Account',
    'auth.switchToSignup': 'Don\'t have an account? Sign up',
    'auth.switchToLogin': 'Already have an account? Sign in',
    'auth.forgotPassword': 'Forgot your password?',
    'auth.resetPassword': 'Reset Password',

    // Common
    'common.loading': 'Loading...',
    'common.error': 'An error occurred',
    'common.tryAgain': 'Try Again',
    'common.cancel': 'Cancel',
    'common.save': 'Save',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.close': 'Close',
    'common.back': 'Back',
    'common.next': 'Next',
    'common.previous': 'Previous',
    'common.submit': 'Submit',
    'common.search': 'Search',
    'common.filter': 'Filter',
    'common.sort': 'Sort',
    'common.view': 'View',
    'common.download': 'Download',
    'common.upload': 'Upload',
    'common.share': 'Share',
    'common.copy': 'Copy',
    'common.print': 'Print',
    'common.help': 'Help',
    'common.settings': 'Settings',
    'common.profile': 'Profile',
    'common.account': 'Account',
    'common.billing': 'Billing',
    'common.privacy': 'Privacy',
    'common.terms': 'Terms',
    'common.support': 'Support',
    'common.feedback': 'Feedback',
    'common.contact': 'Contact',
    'common.about': 'About',
    'common.home': 'Home',
    'common.dashboard': 'Dashboard',
    'common.notifications': 'Notifications',
    'common.messages': 'Messages',
    'common.tasks': 'Tasks',
    'common.calendar': 'Calendar',
    'common.reports': 'Reports',
    'common.analytics': 'Analytics',
    'common.statistics': 'Statistics',
    'common.overview': 'Overview',
    'common.details': 'Details',
    'common.summary': 'Summary',
    'common.history': 'History',
    'common.recent': 'Recent',
    'common.favorites': 'Favorites',
    'common.bookmarks': 'Bookmarks',
    'common.tags': 'Tags',
    'common.categories': 'Categories',
    'common.status': 'Status',
    'common.priority': 'Priority',
    'common.date': 'Date',
    'common.time': 'Time',
    'common.duration': 'Duration',
    'common.location': 'Location',
    'common.description': 'Description',
    'common.notes': 'Notes',
    'common.comments': 'Comments',
    'common.attachments': 'Attachments',
    'common.links': 'Links',
    'common.files': 'Files',
    'common.images': 'Images',
    'common.videos': 'Videos',
    'common.audio': 'Audio',
    'common.documents': 'Documents',
    'common.spreadsheets': 'Spreadsheets',
    'common.presentations': 'Presentations',
    'common.archives': 'Archives',
    'common.folders': 'Folders',
    'common.permissions': 'Permissions',
    'common.access': 'Access',
    'common.security': 'Security',
    'common.backup': 'Backup',
    'common.restore': 'Restore',
    'common.export': 'Export',
    'common.import': 'Import',
    'common.sync': 'Sync',
    'common.refresh': 'Refresh',
    'common.reload': 'Reload',
    'common.reset': 'Reset',
    'common.clear': 'Clear',
    'common.clean': 'Clean',
    'common.optimize': 'Optimize',
    'common.update': 'Update',
    'common.upgrade': 'Upgrade',
    'common.downgrade': 'Downgrade',
    'common.install': 'Install',
    'common.uninstall': 'Uninstall',
    'common.enable': 'Enable',
    'common.disable': 'Disable',
    'common.activate': 'Activate',
    'common.deactivate': 'Deactivate',
    'common.connect': 'Connect',
    'common.disconnect': 'Disconnect',
    'common.online': 'Online',
    'common.offline': 'Offline',
    'common.available': 'Available',
    'common.unavailable': 'Unavailable',
    'common.active': 'Active',
    'common.inactive': 'Inactive',
    'common.enabled': 'Enabled',
    'common.disabled': 'Disabled',
    'common.public': 'Public',
    'common.private': 'Private',
    'common.hidden': 'Hidden',
    'common.visible': 'Visible',
    'common.show': 'Show',
    'common.hide': 'Hide',
    'common.expand': 'Expand',
    'common.collapse': 'Collapse',
    'common.minimize': 'Minimize',
    'common.maximize': 'Maximize',
    'common.fullscreen': 'Full Screen',
    'common.exit': 'Exit',
    'common.quit': 'Quit',
    'common.logout': 'Log Out',
    'common.signin': 'Sign In',
    'common.signup': 'Sign Up',
    'common.register': 'Register',
    'common.login': 'Log In',
    'common.username': 'Username',
    'common.email': 'Email',
    'common.password': 'Password',
    'common.confirmPassword': 'Confirm Password',
    'common.firstName': 'First Name',
    'common.lastName': 'Last Name',
    'common.fullName': 'Full Name',
    'common.displayName': 'Display Name',
    'common.nickname': 'Nickname',
    'common.title': 'Title',
    'common.company': 'Company',
    'common.organization': 'Organization',
    'common.department': 'Department',
    'common.position': 'Position',
    'common.role': 'Role',
    'common.permissions': 'Permissions',
    'common.group': 'Group',
    'common.team': 'Team',
    'common.member': 'Member',
    'common.admin': 'Administrator',
    'common.user': 'User',
    'common.guest': 'Guest',
    'common.owner': 'Owner',
    'common.manager': 'Manager',
    'common.editor': 'Editor',
    'common.viewer': 'Viewer',
    'common.contributor': 'Contributor',
    'common.moderator': 'Moderator',
    'common.subscriber': 'Subscriber',
    'common.follower': 'Follower',
    'common.following': 'Following',
    'common.friend': 'Friend',
    'common.contact': 'Contact',
    'common.colleague': 'Colleague',
    'common.partner': 'Partner',
    'common.client': 'Client',
    'common.customer': 'Customer',
    'common.vendor': 'Vendor',
    'common.supplier': 'Supplier',
    'common.provider': 'Provider',
    'common.service': 'Service',
    'common.product': 'Product',
    'common.item': 'Item',
    'common.resource': 'Resource',
    'common.tool': 'Tool',
    'common.feature': 'Feature',
    'common.option': 'Option',
    'common.setting': 'Setting',
    'common.preference': 'Preference',
    'common.configuration': 'Configuration',
    'common.customization': 'Customization',
    'common.theme': 'Theme',
    'common.layout': 'Layout',
    'common.design': 'Design',
    'common.style': 'Style',
    'common.color': 'Color',
    'common.font': 'Font',
    'common.size': 'Size',
    'common.width': 'Width',
    'common.height': 'Height',
    'common.length': 'Length',
    'common.weight': 'Weight',
    'common.volume': 'Volume',
    'common.quantity': 'Quantity',
    'common.amount': 'Amount',
    'common.total': 'Total',
    'common.subtotal': 'Subtotal',
    'common.tax': 'Tax',
    'common.discount': 'Discount',
    'common.price': 'Price',
    'common.cost': 'Cost',
    'common.fee': 'Fee',
    'common.charge': 'Charge',
    'common.payment': 'Payment',
    'common.invoice': 'Invoice',
    'common.receipt': 'Receipt',
    'common.order': 'Order',
    'common.purchase': 'Purchase',
    'common.sale': 'Sale',
    'common.transaction': 'Transaction',
    'common.transfer': 'Transfer',
    'common.exchange': 'Exchange',
    'common.refund': 'Refund',
    'common.credit': 'Credit',
    'common.debit': 'Debit',
    'common.balance': 'Balance',
    'common.account': 'Account',
    'common.budget': 'Budget',
    'common.finance': 'Finance',
    'common.revenue': 'Revenue',
    'common.profit': 'Profit',
    'common.loss': 'Loss',
    'common.expense': 'Expense',
    'common.income': 'Income',
    'common.salary': 'Salary',
    'common.wage': 'Wage',
    'common.bonus': 'Bonus',
    'common.commission': 'Commission',
    'common.reward': 'Reward',
    'common.incentive': 'Incentive',
    'common.benefit': 'Benefit',
    'common.insurance': 'Insurance',
    'common.coverage': 'Coverage',
    'common.policy': 'Policy',
    'common.plan': 'Plan',
    'common.package': 'Package',
    'common.bundle': 'Bundle',
    'common.subscription': 'Subscription',
    'common.membership': 'Membership',
    'common.license': 'License',
    'common.permit': 'Permit',
    'common.certificate': 'Certificate',
    'common.diploma': 'Diploma',
    'common.degree': 'Degree',
    'common.qualification': 'Qualification',
    'common.skill': 'Skill',
    'common.ability': 'Ability',
    'common.talent': 'Talent',
    'common.expertise': 'Expertise',
    'common.experience': 'Experience',
    'common.knowledge': 'Knowledge',
    'common.education': 'Education',
    'common.training': 'Training',
    'common.course': 'Course',
    'common.lesson': 'Lesson',
    'common.tutorial': 'Tutorial',
    'common.guide': 'Guide',
    'common.manual': 'Manual',
    'common.documentation': 'Documentation',
    'common.instructions': 'Instructions',
    'common.steps': 'Steps',
    'common.procedure': 'Procedure',
    'common.process': 'Process',
    'common.method': 'Method',
    'common.technique': 'Technique',
    'common.approach': 'Approach',
    'common.strategy': 'Strategy',
    'common.plan': 'Plan',
    'common.goal': 'Goal',
    'common.objective': 'Objective',
    'common.target': 'Target',
    'common.milestone': 'Milestone',
    'common.deadline': 'Deadline',
    'common.schedule': 'Schedule',
    'common.timeline': 'Timeline',
    'common.agenda': 'Agenda',
    'common.event': 'Event',
    'common.meeting': 'Meeting',
    'common.appointment': 'Appointment',
    'common.session': 'Session',
    'common.class': 'Class',
    'common.workshop': 'Workshop',
    'common.seminar': 'Seminar',
    'common.conference': 'Conference',
    'common.presentation': 'Presentation',
    'common.demo': 'Demo',
    'common.preview': 'Preview',
    'common.sample': 'Sample',
    'common.example': 'Example',
    'common.template': 'Template',
    'common.model': 'Model',
    'common.prototype': 'Prototype',
    'common.draft': 'Draft',
    'common.version': 'Version',
    'common.revision': 'Revision',
    'common.edition': 'Edition',
    'common.release': 'Release',
    'common.build': 'Build',
    'common.deployment': 'Deployment',
    'common.publication': 'Publication',
    'common.launch': 'Launch',
    'common.announcement': 'Announcement',
    'common.news': 'News',
    'common.update': 'Update',
    'common.patch': 'Patch',
    'common.fix': 'Fix',
    'common.bug': 'Bug',
    'common.issue': 'Issue',
    'common.problem': 'Problem',
    'common.error': 'Error',
    'common.warning': 'Warning',
    'common.alert': 'Alert',
    'common.notice': 'Notice',
    'common.message': 'Message',
    'common.notification': 'Notification',
    'common.reminder': 'Reminder',
    'common.note': 'Note',
    'common.memo': 'Memo',
    'common.announcement': 'Announcement',
    'common.bulletin': 'Bulletin',
    'common.newsletter': 'Newsletter',
    'common.blog': 'Blog',
    'common.article': 'Article',
    'common.post': 'Post',
    'common.entry': 'Entry',
    'common.record': 'Record',
    'common.log': 'Log',
    'common.journal': 'Journal',
    'common.diary': 'Diary',
    'common.book': 'Book',
    'common.chapter': 'Chapter',
    'common.section': 'Section',
    'common.page': 'Page',
    'common.paragraph': 'Paragraph',
    'common.sentence': 'Sentence',
    'common.word': 'Word',
    'common.text': 'Text',
    'common.content': 'Content',
    'common.data': 'Data',
    'common.information': 'Information',
    'common.details': 'Details',
    'common.facts': 'Facts',
    'common.statistics': 'Statistics',
    'common.metrics': 'Metrics',
    'common.measurement': 'Measurement',
    'common.value': 'Value',
    'common.number': 'Number',
    'common.count': 'Count',
    'common.score': 'Score',
    'common.rating': 'Rating',
    'common.rank': 'Rank',
    'common.grade': 'Grade',
    'common.level': 'Level',
    'common.stage': 'Stage',
    'common.phase': 'Phase',
    'common.step': 'Step',
    'common.progress': 'Progress',
    'common.status': 'Status',
    'common.state': 'State',
    'common.condition': 'Condition',
    'common.situation': 'Situation',
    'common.context': 'Context',
    'common.environment': 'Environment',
    'common.setting': 'Setting',
    'common.location': 'Location',
    'common.place': 'Place',
    'common.position': 'Position',
    'common.address': 'Address',
    'common.country': 'Country',
    'common.state': 'State',
    'common.city': 'City',
    'common.zip': 'ZIP Code',
    'common.phone': 'Phone',
    'common.mobile': 'Mobile',
    'common.fax': 'Fax',
    'common.website': 'Website',
    'common.url': 'URL',
    'common.link': 'Link',
    'common.connection': 'Connection',
    'common.network': 'Network',
    'common.internet': 'Internet',
    'common.web': 'Web',
    'common.online': 'Online',
    'common.offline': 'Offline',
    'common.digital': 'Digital',
    'common.electronic': 'Electronic',
    'common.virtual': 'Virtual',
    'common.remote': 'Remote',
    'common.local': 'Local',
    'common.global': 'Global',
    'common.international': 'International',
    'common.national': 'National',
    'common.regional': 'Regional',
    'common.local': 'Local',
    'common.community': 'Community',
    'common.group': 'Group',
    'common.team': 'Team',
    'common.organization': 'Organization',
    'common.company': 'Company',
    'common.business': 'Business',
    'common.enterprise': 'Enterprise',
    'common.corporation': 'Corporation',
    'common.agency': 'Agency',
    'common.institution': 'Institution',
    'common.association': 'Association',
    'common.society': 'Society',
    'common.club': 'Club',
    'common.union': 'Union',
    'common.federation': 'Federation',
    'common.alliance': 'Alliance',
    'common.partnership': 'Partnership',
    'common.collaboration': 'Collaboration',
    'common.cooperation': 'Cooperation',
    'common.teamwork': 'Teamwork',
    'common.coordination': 'Coordination',
    'common.communication': 'Communication',
    'common.conversation': 'Conversation',
    'common.discussion': 'Discussion',
    'common.dialogue': 'Dialogue',
    'common.debate': 'Debate',
    'common.negotiation': 'Negotiation',
    'common.agreement': 'Agreement',
    'common.contract': 'Contract',
    'common.deal': 'Deal',
    'common.arrangement': 'Arrangement',
    'common.understanding': 'Understanding',
    'common.consensus': 'Consensus',
    'common.decision': 'Decision',
    'common.choice': 'Choice',
    'common.selection': 'Selection',
    'common.option': 'Option',
    'common.alternative': 'Alternative',
    'common.possibility': 'Possibility',
    'common.opportunity': 'Opportunity',
    'common.chance': 'Chance',
    'common.risk': 'Risk',
    'common.challenge': 'Challenge',
    'common.difficulty': 'Difficulty',
    'common.obstacle': 'Obstacle',
    'common.barrier': 'Barrier',
    'common.limitation': 'Limitation',
    'common.restriction': 'Restriction',
    'common.constraint': 'Constraint',
    'common.requirement': 'Requirement',
    'common.condition': 'Condition',
    'common.criteria': 'Criteria',
    'common.standard': 'Standard',
    'common.specification': 'Specification',
    'common.guideline': 'Guideline',
    'common.rule': 'Rule',
    'common.regulation': 'Regulation',
    'common.law': 'Law',
    'common.policy': 'Policy',
    'common.procedure': 'Procedure',
    'common.protocol': 'Protocol',
    'common.practice': 'Practice',
    'common.custom': 'Custom',
    'common.tradition': 'Tradition',
    'common.culture': 'Culture',
    'common.heritage': 'Heritage',
    'common.history': 'History',
    'common.background': 'Background',
    'common.origin': 'Origin',
    'common.source': 'Source',
    'common.reference': 'Reference',
    'common.citation': 'Citation',
    'common.quote': 'Quote',
    'common.excerpt': 'Excerpt',
    'common.extract': 'Extract',
    'common.summary': 'Summary',
    'common.overview': 'Overview',
    'common.introduction': 'Introduction',
    'common.conclusion': 'Conclusion',
    'common.result': 'Result',
    'common.outcome': 'Outcome',
    'common.achievement': 'Achievement',
    'common.success': 'Success',
    'common.failure': 'Failure',
    'common.improvement': 'Improvement',
    'common.enhancement': 'Enhancement',
    'common.optimization': 'Optimization',
    'common.development': 'Development',
    'common.growth': 'Growth',
    'common.expansion': 'Expansion',
    'common.extension': 'Extension',
    'common.addition': 'Addition',
    'common.supplement': 'Supplement',
    'common.complement': 'Complement',
    'common.attachment': 'Attachment',
    'common.appendix': 'Appendix',
    'common.footnote': 'Footnote',
    'common.annotation': 'Annotation',
    'common.comment': 'Comment',
    'common.remark': 'Remark',
    'common.observation': 'Observation',
    'common.opinion': 'Opinion',
    'common.view': 'View',
    'common.perspective': 'Perspective',
    'common.viewpoint': 'Viewpoint',
    'common.standpoint': 'Standpoint',
    'common.position': 'Position',
    'common.stance': 'Stance',
    'common.attitude': 'Attitude',
    'common.approach': 'Approach',
    'common.method': 'Method',
    'common.way': 'Way',
    'common.manner': 'Manner',
    'common.style': 'Style',
    'common.fashion': 'Fashion',
    'common.trend': 'Trend',
    'common.pattern': 'Pattern',
    'common.design': 'Design',
    'common.structure': 'Structure',
    'common.format': 'Format',
    'common.layout': 'Layout',
    'common.arrangement': 'Arrangement',
    'common.organization': 'Organization',
    'common.order': 'Order',
    'common.sequence': 'Sequence',
    'common.series': 'Series',
    'common.chain': 'Chain',
    'common.cycle': 'Cycle',
    'common.loop': 'Loop',
    'common.round': 'Round',
    'common.turn': 'Turn',
    'common.rotation': 'Rotation',
    'common.revolution': 'Revolution',
    'common.change': 'Change',
    'common.transformation': 'Transformation',
    'common.conversion': 'Conversion',
    'common.modification': 'Modification',
    'common.adjustment': 'Adjustment',
    'common.adaptation': 'Adaptation',
    'common.customization': 'Customization',
    'common.personalization': 'Personalization',
    'common.individualization': 'Individualization',
    'common.specialization': 'Specialization',
    'common.generalization': 'Generalization',
    'common.simplification': 'Simplification',
    'common.complication': 'Complication',
    'common.complexity': 'Complexity',
    'common.simplicity': 'Simplicity',
    'common.clarity': 'Clarity',
    'common.transparency': 'Transparency',
    'common.visibility': 'Visibility',
    'common.accessibility': 'Accessibility',
    'common.availability': 'Availability',
    'common.reliability': 'Reliability',
    'common.stability': 'Stability',
    'common.consistency': 'Consistency',
    'common.continuity': 'Continuity',
    'common.sustainability': 'Sustainability',
    'common.durability': 'Durability',
    'common.longevity': 'Longevity',
    'common.permanence': 'Permanence',
    'common.temporality': 'Temporality',
    'common.flexibility': 'Flexibility',
    'common.adaptability': 'Adaptability',
    'common.versatility': 'Versatility',
    'common.compatibility': 'Compatibility',
    'common.interoperability': 'Interoperability',
    'common.integration': 'Integration',
    'common.synchronization': 'Synchronization',
    'common.coordination': 'Coordination',
    'common.alignment': 'Alignment',
    'common.balance': 'Balance',
    'common.harmony': 'Harmony',
    'common.unity': 'Unity',
    'common.diversity': 'Diversity',
    'common.variety': 'Variety',
    'common.range': 'Range',
    'common.scope': 'Scope',
    'common.scale': 'Scale',
    'common.magnitude': 'Magnitude',
    'common.dimension': 'Dimension',
    'common.aspect': 'Aspect',
    'common.factor': 'Factor',
    'common.element': 'Element',
    'common.component': 'Component',
    'common.part': 'Part',
    'common.piece': 'Piece',
    'common.portion': 'Portion',
    'common.segment': 'Segment',
    'common.fraction': 'Fraction',
    'common.percentage': 'Percentage',
    'common.ratio': 'Ratio',
    'common.proportion': 'Proportion',
    'common.relationship': 'Relationship',
    'common.connection': 'Connection',
    'common.association': 'Association',
    'common.correlation': 'Correlation',
    'common.correspondence': 'Correspondence',
    'common.similarity': 'Similarity',
    'common.difference': 'Difference',
    'common.distinction': 'Distinction',
    'common.comparison': 'Comparison',
    'common.contrast': 'Contrast',
    'common.opposition': 'Opposition',
    'common.conflict': 'Conflict',
    'common.contradiction': 'Contradiction',
    'common.paradox': 'Paradox',
    'common.dilemma': 'Dilemma',
    'common.problem': 'Problem',
    'common.issue': 'Issue',
    'common.concern': 'Concern',
    'common.matter': 'Matter',
    'common.subject': 'Subject',
    'common.topic': 'Topic',
    'common.theme': 'Theme',
    'common.focus': 'Focus',
    'common.emphasis': 'Emphasis',
    'common.priority': 'Priority',
    'common.importance': 'Importance',
    'common.significance': 'Significance',
    'common.meaning': 'Meaning',
    'common.sense': 'Sense',
    'common.purpose': 'Purpose',
    'common.intention': 'Intention',
    'common.goal': 'Goal',
    'common.aim': 'Aim',
    'common.objective': 'Objective',
    'common.mission': 'Mission',
    'common.vision': 'Vision',
    'common.dream': 'Dream',
    'common.hope': 'Hope',
    'common.wish': 'Wish',
    'common.desire': 'Desire',
    'common.want': 'Want',
    'common.need': 'Need',
    'common.requirement': 'Requirement',
    'common.demand': 'Demand',
    'common.request': 'Request',
    'common.inquiry': 'Inquiry',
    'common.question': 'Question',
    'common.answer': 'Answer',
    'common.response': 'Response',
    'common.reply': 'Reply',
    'common.feedback': 'Feedback',
    'common.input': 'Input',
    'common.output': 'Output',
    'common.result': 'Result',
    'common.outcome': 'Outcome',
    'common.consequence': 'Consequence',
    'common.effect': 'Effect',
    'common.impact': 'Impact',
    'common.influence': 'Influence',
    'common.power': 'Power',
    'common.force': 'Force',
    'common.strength': 'Strength',
    'common.weakness': 'Weakness',
    'common.advantage': 'Advantage',
    'common.disadvantage': 'Disadvantage',
    'common.benefit': 'Benefit',
    'common.cost': 'Cost',
    'common.value': 'Value',
    'common.worth': 'Worth',
    'common.merit': 'Merit',
    'common.quality': 'Quality',
    'common.quantity': 'Quantity',
    'common.measure': 'Measure',
    'common.unit': 'Unit',
    'common.scale': 'Scale',
    'common.standard': 'Standard',
    'common.benchmark': 'Benchmark',
    'common.reference': 'Reference',
    'common.baseline': 'Baseline',
    'common.foundation': 'Foundation',
    'common.basis': 'Basis',
    'common.ground': 'Ground',
    'common.platform': 'Platform',
    'common.framework': 'Framework',
    'common.structure': 'Structure',
    'common.system': 'System',
    'common.network': 'Network',
    'common.infrastructure': 'Infrastructure',
    'common.architecture': 'Architecture',
    'common.design': 'Design',
    'common.blueprint': 'Blueprint',
    'common.plan': 'Plan',
    'common.scheme': 'Scheme',
    'common.strategy': 'Strategy',
    'common.tactic': 'Tactic',
    'common.approach': 'Approach',
    'common.method': 'Method',
    'common.technique': 'Technique',
    'common.procedure': 'Procedure',
    'common.process': 'Process',
    'common.workflow': 'Workflow',
    'common.pipeline': 'Pipeline',
    'common.chain': 'Chain',
    'common.sequence': 'Sequence',
    'common.order': 'Order',
    'common.hierarchy': 'Hierarchy',
    'common.level': 'Level',
    'common.tier': 'Tier',
    'common.layer': 'Layer',
    'common.stage': 'Stage',
    'common.phase': 'Phase',
    'common.step': 'Step',
    'common.milestone': 'Milestone',
    'common.checkpoint': 'Checkpoint',
    'common.marker': 'Marker',
    'common.indicator': 'Indicator',
    'common.signal': 'Signal',
    'common.sign': 'Sign',
    'common.symbol': 'Symbol',
    'common.icon': 'Icon',
    'common.image': 'Image',
    'common.picture': 'Picture',
    'common.photo': 'Photo',
    'common.graphic': 'Graphic',
    'common.illustration': 'Illustration',
    'common.diagram': 'Diagram',
    'common.chart': 'Chart',
    'common.graph': 'Graph',
    'common.table': 'Table',
    'common.list': 'List',
    'common.menu': 'Menu',
    'common.index': 'Index',
    'common.catalog': 'Catalog',
    'common.directory': 'Directory',
    'common.database': 'Database',
    'common.repository': 'Repository',
    'common.library': 'Library',
    'common.archive': 'Archive',
    'common.collection': 'Collection',
    'common.set': 'Set',
    'common.group': 'Group',
    'common.cluster': 'Cluster',
    'common.batch': 'Batch',
    'common.bundle': 'Bundle',
    'common.package': 'Package',
    'common.container': 'Container',
    'common.box': 'Box',
    'common.folder': 'Folder',
    'common.file': 'File',
    'common.document': 'Document',
    'common.record': 'Record',
    'common.entry': 'Entry',
    'common.item': 'Item',
    'common.object': 'Object',
    'common.entity': 'Entity',
    'common.instance': 'Instance',
    'common.specimen': 'Specimen',
    'common.sample': 'Sample',
    'common.example': 'Example',
    'common.case': 'Case',
    'common.scenario': 'Scenario',
    'common.situation': 'Situation',
    'common.circumstance': 'Circumstance',
    'common.condition': 'Condition',
    'common.state': 'State',
    'common.status': 'Status',
    'common.mode': 'Mode',
    'common.setting': 'Setting',
    'common.configuration': 'Configuration',
    'common.setup': 'Setup',
    'common.installation': 'Installation',
    'common.deployment': 'Deployment',
    'common.implementation': 'Implementation',
    'common.execution': 'Execution',
    'common.operation': 'Operation',
    'common.function': 'Function',
    'common.action': 'Action',
    'common.activity': 'Activity',
    'common.task': 'Task',
    'common.job': 'Job',
    'common.work': 'Work',
    'common.project': 'Project',
    'common.assignment': 'Assignment',
    'common.mission': 'Mission',
    'common.duty': 'Duty',
    'common.responsibility': 'Responsibility',
    'common.obligation': 'Obligation',
    'common.commitment': 'Commitment',
    'common.promise': 'Promise',
    'common.pledge': 'Pledge',
    'common.guarantee': 'Guarantee',
    'common.warranty': 'Warranty',
    'common.assurance': 'Assurance',
    'common.confidence': 'Confidence',
    'common.trust': 'Trust',
    'common.faith': 'Faith',
    'common.belief': 'Belief',
    'common.conviction': 'Conviction',
    'common.opinion': 'Opinion',
    'common.thought': 'Thought',
    'common.idea': 'Idea',
    'common.concept': 'Concept',
    'common.notion': 'Notion',
    'common.theory': 'Theory',
    'common.hypothesis': 'Hypothesis',
    'common.assumption': 'Assumption',
    'common.presumption': 'Presumption',
    'common.supposition': 'Supposition',
    'common.speculation': 'Speculation',
    'common.conjecture': 'Conjecture',
    'common.guess': 'Guess',
    'common.estimate': 'Estimate',
    'common.calculation': 'Calculation',
    'common.computation': 'Computation',
    'common.analysis': 'Analysis',
    'common.examination': 'Examination',
    'common.investigation': 'Investigation',
    'common.research': 'Research',
    'common.study': 'Study',
    'common.survey': 'Survey',
    'common.review': 'Review',
    'common.assessment': 'Assessment',
    'common.evaluation': 'Evaluation',
    'common.appraisal': 'Appraisal',
    'common.judgment': 'Judgment',
    'common.decision': 'Decision',
    'common.determination': 'Determination',
    'common.resolution': 'Resolution',
    'common.conclusion': 'Conclusion',
    'common.finding': 'Finding',
    'common.discovery': 'Discovery',
    'common.revelation': 'Revelation',
    'common.insight': 'Insight',
    'common.understanding': 'Understanding',
    'common.comprehension': 'Comprehension',
    'common.knowledge': 'Knowledge',
    'common.information': 'Information',
    'common.data': 'Data',
    'common.facts': 'Facts',
    'common.details': 'Details',
    'common.particulars': 'Particulars',
    'common.specifics': 'Specifics',
    'common.specifications': 'Specifications',
    'common.requirements': 'Requirements',
    'common.criteria': 'Criteria',
    'common.standards': 'Standards',
    'common.guidelines': 'Guidelines',
    'common.rules': 'Rules',
    'common.regulations': 'Regulations',
    'common.laws': 'Laws',
    'common.policies': 'Policies',
    'common.procedures': 'Procedures',
    'common.protocols': 'Protocols',
    'common.practices': 'Practices',
    'common.customs': 'Customs',
    'common.traditions': 'Traditions',
    'common.conventions': 'Conventions',
    'common.norms': 'Norms',
    'common.values': 'Values',
    'common.principles': 'Principles',
    'common.beliefs': 'Beliefs',
    'common.ideals': 'Ideals',
    'common.goals': 'Goals',
    'common.objectives': 'Objectives',
    'common.targets': 'Targets',
    'common.aims': 'Aims',
    'common.purposes': 'Purposes',
    'common.intentions': 'Intentions',
    'common.plans': 'Plans',
    'common.strategies': 'Strategies',
    'common.tactics': 'Tactics',
    'common.approaches': 'Approaches',
    'common.methods': 'Methods',
    'common.techniques': 'Techniques',
    'common.ways': 'Ways',
    'common.means': 'Means',
    'common.tools': 'Tools',
    'common.instruments': 'Instruments',
    'common.devices': 'Devices',
    'common.equipment': 'Equipment',
    'common.machinery': 'Machinery',
    'common.apparatus': 'Apparatus',
    'common.system': 'System',
    'common.mechanism': 'Mechanism',
    'common.engine': 'Engine',
    'common.motor': 'Motor',
    'common.machine': 'Machine',
    'common.robot': 'Robot',
    'common.automation': 'Automation',
    'common.technology': 'Technology',
    'common.innovation': 'Innovation',
    'common.invention': 'Invention',
    'common.creation': 'Creation',
    'common.development': 'Development',
    'common.advancement': 'Advancement',
    'common.progress': 'Progress',
    'common.improvement': 'Improvement',
    'common.enhancement': 'Enhancement',
    'common.upgrade': 'Upgrade',
    'common.update': 'Update',
    'common.revision': 'Revision',
    'common.modification': 'Modification',
    'common.change': 'Change',
    'common.alteration': 'Alteration',
    'common.adjustment': 'Adjustment',
    'common.adaptation': 'Adaptation',
    'common.transformation': 'Transformation',
    'common.conversion': 'Conversion',
    'common.translation': 'Translation',
    'common.interpretation': 'Interpretation',
    'common.explanation': 'Explanation',
    'common.clarification': 'Clarification',
    'common.description': 'Description',
    'common.definition': 'Definition',
    'common.meaning': 'Meaning',
    'common.significance': 'Significance',
    'common.importance': 'Importance',
    'common.relevance': 'Relevance',
    'common.applicability': 'Applicability',
    'common.utility': 'Utility',
    'common.usefulness': 'Usefulness',
    'common.effectiveness': 'Effectiveness',
    'common.efficiency': 'Efficiency',
    'common.productivity': 'Productivity',
    'common.performance': 'Performance',
    'common.quality': 'Quality',
    'common.excellence': 'Excellence',
    'common.superiority': 'Superiority',
    'common.advantage': 'Advantage',
    'common.benefit': 'Benefit',
    'common.gain': 'Gain',
    'common.profit': 'Profit',
    'common.return': 'Return',
    'common.yield': 'Yield',
    'common.outcome': 'Outcome',
    'common.result': 'Result',
    'common.consequence': 'Consequence',
    'common.effect': 'Effect',
    'common.impact': 'Impact',
    'common.influence': 'Influence',
    'common.power': 'Power',
    'common.authority': 'Authority',
    'common.control': 'Control',
    'common.command': 'Command',
    'common.leadership': 'Leadership',
    'common.management': 'Management',
    'common.administration': 'Administration',
    'common.governance': 'Governance',
    'common.supervision': 'Supervision',
    'common.oversight': 'Oversight',
    'common.monitoring': 'Monitoring',
    'common.tracking': 'Tracking',
    'common.observation': 'Observation',
    'common.surveillance': 'Surveillance',
    'common.inspection': 'Inspection',
    'common.examination': 'Examination',
    'common.audit': 'Audit',
    'common.check': 'Check',
    'common.test': 'Test',
    'common.trial': 'Trial',
    'common.experiment': 'Experiment',
    'common.study': 'Study',
    'common.research': 'Research',
    'common.investigation': 'Investigation',
    'common.inquiry': 'Inquiry',
    'common.exploration': 'Exploration',
    'common.discovery': 'Discovery',
    'common.finding': 'Finding',
    'common.detection': 'Detection',
    'common.identification': 'Identification',
    'common.recognition': 'Recognition',
    'common.acknowledgment': 'Acknowledgment',
    'common.appreciation': 'Appreciation',
    'common.gratitude': 'Gratitude',
    'common.thanks': 'Thanks',
    'common.credit': 'Credit',
    'common.honor': 'Honor',
    'common.respect': 'Respect',
    'common.admiration': 'Admiration',
    'common.praise': 'Praise',
    'common.compliment': 'Compliment',
    'common.congratulations': 'Congratulations',
    'common.celebration': 'Celebration',
    'common.party': 'Party',
    'common.event': 'Event',
    'common.occasion': 'Occasion',
    'common.ceremony': 'Ceremony',
    'common.ritual': 'Ritual',
    'common.tradition': 'Tradition',
    'common.custom': 'Custom',
    'common.practice': 'Practice',
    'common.habit': 'Habit',
    'common.routine': 'Routine',
    'common.pattern': 'Pattern',
    'common.cycle': 'Cycle',
    'common.rhythm': 'Rhythm',
    'common.tempo': 'Tempo',
    'common.pace': 'Pace',
    'common.speed': 'Speed',
    'common.velocity': 'Velocity',
    'common.acceleration': 'Acceleration',
    'common.momentum': 'Momentum',
    'common.force': 'Force',
    'common.energy': 'Energy',
    'common.power': 'Power',
    'common.strength': 'Strength',
    'common.intensity': 'Intensity',
    'common.magnitude': 'Magnitude',
    'common.scale': 'Scale',
    'common.size': 'Size',
    'common.dimension': 'Dimension',
    'common.measure': 'Measure',
    'common.extent': 'Extent',
    'common.scope': 'Scope',
    'common.range': 'Range',
    'common.span': 'Span',
    'common.reach': 'Reach',
    'common.coverage': 'Coverage',
    'common.area': 'Area',
    'common.region': 'Region',
    'common.zone': 'Zone',
    'common.territory': 'Territory',
    'common.domain': 'Domain',
    'common.field': 'Field',
    'common.sphere': 'Sphere',
    'common.realm': 'Realm',
    'common.world': 'World',
    'common.universe': 'Universe',
    'common.space': 'Space',
  },
  es: {
    // Navigation
    'nav.features': 'Características',
    'nav.pricing': 'Precios',
    'nav.about': 'Acerca de',
    'nav.contact': 'Contacto',
    'nav.login': 'Iniciar Sesión',
    'nav.signup': 'Registrarse',
    'nav.dashboard': 'Panel',
    'nav.logout': 'Cerrar Sesión',

    // Hero Section
    'hero.title': 'El Futuro del Aprendizaje con IA Está Aquí',
    'hero.subtitle': 'Experimenta la educación personalizada con nuestro tutor de IA avanzado que se adapta a tu estilo de aprendizaje, proporciona retroalimentación instantánea y hace que el aprendizaje sea atractivo a través de la gamificación.',

    // CTA
    'cta.start': 'Comenzar a Aprender Ahora',
    'cta.demo': 'Probar Demo',
    'cta.trial': 'Comenzar Prueba Gratuita',

    // Features Section  
    'features.section.title': 'Características Poderosas para el Aprendizaje Moderno',
    'features.section.subtitle': 'Descubre cómo nuestra plataforma impulsada por IA transforma la educación a través de experiencias de aprendizaje personalizadas.',
    'features.adaptive.title': 'Aprendizaje Adaptativo con IA',
    'features.adaptive.desc': 'Nuestra IA se adapta a tu ritmo y estilo de aprendizaje, proporcionando contenido personalizado y niveles de dificultad.',
    'features.voice.title': 'Conversaciones por Voz',
    'features.voice.desc': 'Practica hablar y escuchar con interacciones de voz naturales impulsadas por IA avanzada.',
    'features.content.title': 'Generación Dinámica de Contenido',
    'features.content.desc': 'Obtén problemas de práctica ilimitados, explicaciones y materiales de aprendizaje generados en tiempo real.',
    'features.gamified.title': 'Aprendizaje Gamificado',
    'features.gamified.desc': 'Mantente motivado con logros, niveles y recompensas que hacen que el aprendizaje sea divertido y atractivo.',
    'features.analytics.title': 'Análisis Avanzados',
    'features.analytics.desc': 'Rastrea tu progreso con ideas detalladas y recomendaciones de aprendizaje personalizadas.',
    'features.collaborative.title': 'Aprendizaje Colaborativo',
    'features.collaborative.desc': 'Conéctate con compañeros y maestros en un entorno de aprendizaje seguro y moderado.',

    // Other sections...
    'subjects.title': 'Cobertura Integral de Materias',
    'subjects.subtitle': 'Domina cualquier materia con nuestra tutoría impulsada por IA en todas las disciplinas académicas.',
    
    // Progress
    'progress.title': 'Progreso de Aprendizaje',
    'progress.description': 'Rastrea tu viaje de aprendizaje y logros',
    'progress.demoTitle': 'Progreso Demo de Aprendizaje',
    'progress.demoDescription': 'Esta es una demo que muestra cómo se vería tu panel de progreso',
    'progress.demoNotice': 'Estos son datos de demostración. ¡Regístrate para rastrear tu progreso real!',
    'progress.notAvailable': 'El seguimiento del progreso no está disponible para tu tipo de cuenta.',
    'progress.tabs.monitoring': 'Resumen',
    'progress.tabs.childProgress': 'Progreso del Niño',
    'progress.tabs.quests': 'Misiones',
    'progress.tabs.achievements': 'Logros',
    'progress.tabs.subjects': 'Materias',
    'progress.tabs.analytics': 'Análisis',

    // Chat
    'chat.navigation.chat': 'Chat',
    'chat.navigation.progress': 'Progreso',
    'chat.navigation.modules': 'Módulos',
    'chat.title': 'Chat de Aprendizaje IA',
    'chat.subtitle': '¡Pregúntame cualquier cosa sobre tus estudios!',
    'chat.placeholder': 'Escribe tu pregunta aquí...',
    'chat.send': 'Enviar',
    'chat.voice': 'Chat por Voz',
    'chat.clear': 'Limpiar Chat',

    // Modules
    'modules.title': 'Módulos de Aprendizaje',
    'modules.description': 'Explora rutas de aprendizaje estructuradas en diferentes materias',
    'modules.demoTitle': 'Módulos Demo de Aprendizaje',
    'modules.demoDescription': 'Esto muestra los módulos de aprendizaje disponibles en nuestra plataforma',
    'modules.demoNotice': 'Este es contenido de demostración. ¡Regístrate para acceder a los módulos de aprendizaje completos!',
    'modules.coming.soon': '¡Más módulos próximamente!',

    // Testing
    'testing.title': 'Pruebas',
    'testing.createTest': 'Crear Prueba Personalizada',
    'testing.quizLibrary': 'Biblioteca de Cuestionarios',

    // Auth
    'auth.login.title': 'Bienvenido de Vuelta',
    'auth.login.subtitle': 'Inicia sesión para continuar tu viaje de aprendizaje',
    'auth.signup.title': 'Únete a TeachlyAI',
    'auth.signup.subtitle': 'Comienza tu experiencia de aprendizaje personalizada',
    'auth.email': 'Correo Electrónico',
    'auth.password': 'Contraseña',
    'auth.confirmPassword': 'Confirmar Contraseña',
    'auth.login.button': 'Iniciar Sesión',
    'auth.signup.button': 'Crear Cuenta',
    'auth.switchToSignup': '¿No tienes una cuenta? Regístrate',
    'auth.switchToLogin': '¿Ya tienes una cuenta? Inicia sesión',
    'auth.forgotPassword': '¿Olvidaste tu contraseña?',
    'auth.resetPassword': 'Restablecer Contraseña',

    // Common
    'common.loading': 'Cargando...',
    'common.error': 'Ocurrió un error',
    'common.tryAgain': 'Intentar de Nuevo',
    'common.cancel': 'Cancelar',
    'common.save': 'Guardar',
    'common.delete': 'Eliminar',
    'common.edit': 'Editar',
    'common.close': 'Cerrar',
    'common.back': 'Atrás',
    'common.next': 'Siguiente',
    'common.previous': 'Anterior',
    'common.submit': 'Enviar',
    'common.search': 'Buscar',
    'common.filter': 'Filtrar',
    'common.sort': 'Ordenar',
    'common.view': 'Ver',
    'common.download': 'Descargar',
    'common.upload': 'Subir',
    'common.share': 'Compartir',
    'common.copy': 'Copiar',
    'common.print': 'Imprimir',
    'common.help': 'Ayuda',
    'common.settings': 'Configuración',
    'common.profile': 'Perfil',
    'common.account': 'Cuenta',
    'common.billing': 'Facturación',
    'common.privacy': 'Privacidad',
    'common.terms': 'Términos',
    'common.support': 'Soporte',
    'common.feedback': 'Comentarios',
    'common.contact': 'Contacto',
    'common.about': 'Acerca de',
    'common.home': 'Inicio',
    'common.dashboard': 'Panel',
    'common.logout': 'Cerrar Sesión',
    'common.signin': 'Iniciar Sesión',
    'common.signup': 'Registrarse',
    'common.register': 'Registrar',
    'common.login': 'Iniciar Sesión',
    'common.username': 'Nombre de Usuario',
    'common.email': 'Correo Electrónico',
    'common.password': 'Contraseña',
    'common.confirmPassword': 'Confirmar Contraseña',
    'common.firstName': 'Nombre',
    'common.lastName': 'Apellido',
    'common.fullName': 'Nombre Completo',
    'common.displayName': 'Nombre para Mostrar',
    'common.nickname': 'Apodo',
    'common.title': 'Título',
    'common.company': 'Empresa',
    'common.organization': 'Organización',
    'common.department': 'Departamento',
    'common.position': 'Posición',
    'common.role': 'Rol',
    'common.permissions': 'Permisos',
    'common.group': 'Grupo',
    'common.team': 'Equipo',
    'common.member': 'Miembro',
    'common.admin': 'Administrador',
    'common.user': 'Usuario',
    'common.guest': 'Huésped',
    'common.owner': 'Propietario',
    'common.manager': 'Gerente',
    'common.editor': 'Editor',
    'common.viewer': 'Visor',
    'common.contributor': 'Colaborador',
    'common.moderator': 'Moderador',
  },
  fr: {
    // Navigation
    'nav.features': 'Fonctionnalités',
    'nav.pricing': 'Tarifs',
    'nav.about': 'À propos',
    'nav.contact': 'Contact',
    'nav.login': 'Connexion',
    'nav.signup': 'S\'inscrire',
    'nav.dashboard': 'Tableau de bord',
    'nav.logout': 'Déconnexion',

    // Hero Section
    'hero.title': 'L\'Avenir de l\'Apprentissage par IA est Ici',
    'hero.subtitle': 'Découvrez l\'éducation personnalisée avec notre tuteur IA avancé qui s\'adapte à votre style d\'apprentissage, fournit des commentaires instantanés et rend l\'apprentissage engageant grâce à la gamification.',

    // CTA
    'cta.start': 'Commencer à Apprendre Maintenant',
    'cta.demo': 'Essayer la Démo',
    'cta.trial': 'Commencer l\'Essai Gratuit',

    // Features Section
    'features.section.title': 'Fonctionnalités Puissantes pour l\'Apprentissage Moderne',
    'features.section.subtitle': 'Découvrez comment notre plateforme alimentée par l\'IA transforme l\'éducation grâce à des expériences d\'apprentissage personnalisées.',
    
    // Chat
    'chat.navigation.chat': 'Chat',
    'chat.navigation.progress': 'Progrès',
    'chat.navigation.modules': 'Modules',
    
    // Progress
    'progress.title': 'Progrès d\'Apprentissage',
    'progress.description': 'Suivez votre parcours d\'apprentissage et vos réalisations',
    
    // Auth
    'auth.login.title': 'Bon Retour',
    'auth.signup.title': 'Rejoindre TeachlyAI',
    'auth.email': 'E-mail',
    'auth.password': 'Mot de passe',

    // Common
    'common.loading': 'Chargement...',
    'common.error': 'Une erreur s\'est produite',
  },
  de: {
    // Navigation
    'nav.features': 'Funktionen',
    'nav.pricing': 'Preise',
    'nav.about': 'Über uns',
    'nav.contact': 'Kontakt',
    'nav.login': 'Anmelden',
    'nav.signup': 'Registrieren',
    'nav.dashboard': 'Dashboard',
    'nav.logout': 'Abmelden',

    // Hero Section
    'hero.title': 'Die Zukunft des KI-gestützten Lernens ist da',
    'hero.subtitle': 'Erleben Sie personalisierte Bildung mit unserem fortschrittlichen KI-Tutor, der sich an Ihren Lernstil anpasst, sofortiges Feedback gibt und das Lernen durch Gamification spannend macht.',

    // CTA
    'cta.start': 'Jetzt Lernen Beginnen',
    'cta.demo': 'Demo Testen',
    'cta.trial': 'Kostenlose Testversion Starten',

    // Features Section
    'features.section.title': 'Leistungsstarke Funktionen für Modernes Lernen',
    'features.section.subtitle': 'Entdecken Sie, wie unsere KI-gestützte Plattform die Bildung durch personalisierte Lernerfahrungen transformiert.',
    
    // Chat
    'chat.navigation.chat': 'Chat',
    'chat.navigation.progress': 'Fortschritt',
    'chat.navigation.modules': 'Module',
    
    // Progress
    'progress.title': 'Lernfortschritt',
    'progress.description': 'Verfolgen Sie Ihre Lernreise und Erfolge',
    
    // Auth
    'auth.login.title': 'Willkommen zurück',
    'auth.signup.title': 'Bei TeachlyAI anmelden',
    'auth.email': 'E-Mail',
    'auth.password': 'Passwort',

    // Common
    'common.loading': 'Wird geladen...',
    'common.error': 'Ein Fehler ist aufgetreten',
  },
  zh: {
    // Navigation
    'nav.features': '功能',
    'nav.pricing': '定价',
    'nav.about': '关于我们',
    'nav.contact': '联系我们',
    'nav.login': '登录',
    'nav.signup': '注册',
    'nav.dashboard': '仪表板',
    'nav.logout': '退出',

    // Hero Section
    'hero.title': 'AI驱动学习的未来已来',
    'hero.subtitle': '体验个性化教育，我们的先进AI导师适应您的学习风格，提供即时反馈，并通过游戏化使学习变得有趣。',

    // CTA
    'cta.start': '立即开始学习',
    'cta.demo': '试用演示',
    'cta.trial': '开始免费试用',

    // Features Section
    'features.section.title': '现代学习的强大功能',
    'features.section.subtitle': '发现我们的AI驱动平台如何通过个性化学习体验改变教育。',
    
    // Chat
    'chat.navigation.chat': '聊天',
    'chat.navigation.progress': '进度',
    'chat.navigation.modules': '模块',
    
    // Progress
    'progress.title': '学习进度',
    'progress.description': '跟踪您的学习旅程和成就',
    
    // Auth
    'auth.login.title': '欢迎回来',
    'auth.signup.title': '加入TeachlyAI',
    'auth.email': '邮箱',
    'auth.password': '密码',

    // Common
    'common.loading': '加载中...',
    'common.error': '发生错误',
  },
  ja: {
    // Navigation
    'nav.features': '機能',
    'nav.pricing': '料金',
    'nav.about': '概要',
    'nav.contact': 'お問い合わせ',
    'nav.login': 'ログイン',
    'nav.signup': '登録',
    'nav.dashboard': 'ダッシュボード',
    'nav.logout': 'ログアウト',

    // Hero Section
    'hero.title': 'AI駆動学習の未来がここに',
    'hero.subtitle': 'あなたの学習スタイルに適応し、即座にフィードバックを提供し、ゲーミフィケーションを通じて学習を魅力的にする高度なAIチューターで個人化された教育を体験してください。',

    // CTA
    'cta.start': '今すぐ学習を始める',
    'cta.demo': 'デモを試す',
    'cta.trial': '無料トライアルを開始',

    // Features Section
    'features.section.title': '現代学習のための強力な機能',
    'features.section.subtitle': '私たちのAI駆動プラットフォームがパーソナライズされた学習体験を通じて教育をどのように変革するかをご覧ください。',
    
    // Chat
    'chat.navigation.chat': 'チャット',
    'chat.navigation.progress': '進歩',
    'chat.navigation.modules': 'モジュール',
    
    // Progress
    'progress.title': '学習進歩',
    'progress.description': 'あなたの学習の旅と成果を追跡する',
    
    // Auth
    'auth.login.title': 'おかえりなさい',
    'auth.signup.title': 'TeachlyAIに参加',
    'auth.email': 'メール',
    'auth.password': 'パスワード',

    // Common
    'common.loading': '読み込み中...',
    'common.error': 'エラーが発生しました',
  },
  pt: {
    // Navigation
    'nav.features': 'Recursos',
    'nav.pricing': 'Preços',
    'nav.about': 'Sobre',
    'nav.contact': 'Contato',
    'nav.login': 'Entrar',
    'nav.signup': 'Cadastrar',
    'nav.dashboard': 'Painel',
    'nav.logout': 'Sair',

    // Hero Section
    'hero.title': 'O Futuro da Aprendizagem com IA Está Aqui',
    'hero.subtitle': 'Experimente educação personalizada com nosso tutor de IA avançado que se adapta ao seu estilo de aprendizagem, fornece feedback instantâneo e torna o aprendizado envolvente através da gamificação.',

    // CTA
    'cta.start': 'Começar a Aprender Agora',
    'cta.demo': 'Testar Demo',
    'cta.trial': 'Iniciar Teste Grátis',

    // Features Section
    'features.section.title': 'Recursos Poderosos para Aprendizagem Moderna',
    'features.section.subtitle': 'Descubra como nossa plataforma alimentada por IA transforma a educação através de experiências de aprendizagem personalizadas.',
    
    // Chat
    'chat.navigation.chat': 'Chat',
    'chat.navigation.progress': 'Progresso',
    'chat.navigation.modules': 'Módulos',
    
    // Progress
    'progress.title': 'Progresso de Aprendizagem',
    'progress.description': 'Acompanhe sua jornada de aprendizagem e conquistas',
    
    // Auth
    'auth.login.title': 'Bem-vindo de Volta',
    'auth.signup.title': 'Junte-se ao TeachlyAI',
    'auth.email': 'E-mail',
    'auth.password': 'Senha',

    // Common
    'common.loading': 'Carregando...',
    'common.error': 'Ocorreu um erro',
  },
  it: {
    // Navigation
    'nav.features': 'Caratteristiche',
    'nav.pricing': 'Prezzi',
    'nav.about': 'Chi siamo',
    'nav.contact': 'Contatto',
    'nav.login': 'Accedi',
    'nav.signup': 'Registrati',
    'nav.dashboard': 'Dashboard',
    'nav.logout': 'Esci',

    // Hero Section
    'hero.title': 'Il Futuro dell\'Apprendimento con IA è Qui',
    'hero.subtitle': 'Sperimenta l\'educazione personalizzata con il nostro tutor IA avanzato che si adatta al tuo stile di apprendimento, fornisce feedback istantaneo e rende l\'apprendimento coinvolgente attraverso la gamification.',

    // CTA
    'cta.start': 'Inizia ad Imparare Ora',
    'cta.demo': 'Prova Demo',
    'cta.trial': 'Inizia Prova Gratuita',

    // Features Section
    'features.section.title': 'Caratteristiche Potenti per l\'Apprendimento Moderno',
    'features.section.subtitle': 'Scopri come la nostra piattaforma alimentata dall\'IA trasforma l\'educazione attraverso esperienze di apprendimento personalizzate.',
    
    // Chat
    'chat.navigation.chat': 'Chat',
    'chat.navigation.progress': 'Progresso',
    'chat.navigation.modules': 'Moduli',
    
    // Progress
    'progress.title': 'Progresso di Apprendimento',
    'progress.description': 'Traccia il tuo percorso di apprendimento e i risultati',
    
    // Auth
    'auth.login.title': 'Bentornato',
    'auth.signup.title': 'Unisciti a TeachlyAI',
    'auth.email': 'Email',
    'auth.password': 'Password',

    // Common
    'common.loading': 'Caricamento...',
    'common.error': 'Si è verificato un errore',
  },
  ru: {
    // Navigation
    'nav.features': 'Возможности',
    'nav.pricing': 'Цены',
    'nav.about': 'О нас',
    'nav.contact': 'Контакты',
    'nav.login': 'Войти',
    'nav.signup': 'Регистрация',
    'nav.dashboard': 'Панель',
    'nav.logout': 'Выйти',

    // Hero Section
    'hero.title': 'Будущее ИИ-обучения Здесь',
    'hero.subtitle': 'Испытайте персонализированное образование с нашим продвинутым ИИ-репетитором, который адаптируется к вашему стилю обучения, предоставляет мгновенную обратную связь и делает обучение увлекательным через геймификацию.',

    // CTA
    'cta.start': 'Начать Обучение Сейчас',
    'cta.demo': 'Попробовать Демо',
    'cta.trial': 'Начать Бесплатную Пробную Версию',

    // Features Section
    'features.section.title': 'Мощные Возможности для Современного Обучения',
    'features.section.subtitle': 'Узнайте, как наша платформа на основе ИИ трансформирует образование через персонализированные учебные опыты.',
    
    // Chat
    'chat.navigation.chat': 'Чат',
    'chat.navigation.progress': 'Прогресс',
    'chat.navigation.modules': 'Модули',
    
    // Progress
    'progress.title': 'Прогресс Обучения',
    'progress.description': 'Отслеживайте свой путь обучения и достижения',
    
    // Auth
    'auth.login.title': 'Добро пожаловать обратно',
    'auth.signup.title': 'Присоединиться к TeachlyAI',
    'auth.email': 'Эл. почта',
    'auth.password': 'Пароль',

    // Common
    'common.loading': 'Загрузка...',
    'common.error': 'Произошла ошибка',
  },
  ar: {
    // Navigation
    'nav.features': 'الميزات',
    'nav.pricing': 'الأسعار',
    'nav.about': 'حول',
    'nav.contact': 'اتصل',
    'nav.login': 'تسجيل الدخول',
    'nav.signup': 'إنشاء حساب',
    'nav.dashboard': 'لوحة التحكم',
    'nav.logout': 'تسجيل الخروج',

    // Hero Section
    'hero.title': 'مستقبل التعلم بالذكاء الاصطناعي هنا',
    'hero.subtitle': 'اختبر التعليم المخصص مع مدرسنا الذكي المتقدم الذي يتكيف مع أسلوب تعلمك، ويقدم تعليقات فورية ويجعل التعلم مشوقاً من خلال التلعيب.',

    // CTA
    'cta.start': 'ابدأ التعلم الآن',
    'cta.demo': 'جرب العرض التوضيحي',
    'cta.trial': 'ابدأ النسخة التجريبية المجانية',

    // Features Section
    'features.section.title': 'ميزات قوية للتعلم الحديث',
    'features.section.subtitle': 'اكتشف كيف تحول منصتنا المدعومة بالذكاء الاصطناعي التعليم من خلال تجارب التعلم المخصصة.',
    
    // Chat
    'chat.navigation.chat': 'الدردشة',
    'chat.navigation.progress': 'التقدم',
    'chat.navigation.modules': 'الوحدات',
    
    // Progress
    'progress.title': 'تقدم التعلم',
    'progress.description': 'تتبع رحلة التعلم والإنجازات',
    
    // Auth
    'auth.login.title': 'مرحباً بعودتك',
    'auth.signup.title': 'انضم إلى TeachlyAI',
    'auth.email': 'البريد الإلكتروني',
    'auth.password': 'كلمة المرور',

    // Common
    'common.loading': 'جاري التحميل...',
    'common.error': 'حدث خطأ',
  }
};

const getNestedTranslation = (obj: any, path: string): string => {
  return path.split('.').reduce((current, key) => current?.[key], obj) || path;
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>(() => {
    const saved = localStorage.getItem('teachlyai-language');
    return (saved && Object.keys(translations).includes(saved)) ? saved as Language : 'en';
  });

  useEffect(() => {
    localStorage.setItem('teachlyai-language', language);
  }, [language]);

  const t = (key: string): string => {
    const languageTranslations = translations[language] || translations.en;
    return getNestedTranslation(languageTranslations, key) || key;
  };

  const value = {
    language,
    setLanguage,
    t
  };

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
