import { useState } from 'react';
import PptxGenJS from 'pptxgenjs';
import { supabase } from '@/integrations/supabase/client';
import { useLanguage } from '@/contexts/LanguageContext';
import { toast } from '@/hooks/use-toast';

export interface PresentationSlide {
  slideNumber: number;
  title: string;
  content: string[];
  notes?: string;
  visualSuggestion?: string;
}

export interface QuizQuestion {
  question: string;
  options: string[];
  correctAnswer: string;
  explanation: string;
}

export interface GeneratedPresentation {
  title: string;
  slides: PresentationSlide[];
  quizQuestions?: QuizQuestion[];
}

export interface PresentationSettings {
  topic: string;
  gradeLevel: string;
  slideCount: number;
  style: 'educational' | 'fun' | 'visual' | 'concise';
  includeQuiz: boolean;
  includeExamples: boolean;
}

const COLORS = {
  primary: '4F46E5',
  secondary: '7C3AED',
  accent: '06B6D4',
  success: '10B981',
  warning: 'F59E0B',
  danger: 'EF4444',
  dark: '1F2937',
  light: 'F9FAFB',
  white: 'FFFFFF',
};

const STYLE_COLORS: Record<string, { primary: string; secondary: string; accent: string }> = {
  educational: { primary: '1E40AF', secondary: '3B82F6', accent: '60A5FA' },
  fun: { primary: 'EC4899', secondary: 'F472B6', accent: 'FBBF24' },
  visual: { primary: '059669', secondary: '10B981', accent: '34D399' },
  concise: { primary: '374151', secondary: '6B7280', accent: '9CA3AF' },
};

export const useEducationalPresentationGenerator = () => {
  const [isGenerating, setIsGenerating] = useState(false);
  const [generatedPresentation, setGeneratedPresentation] = useState<GeneratedPresentation | null>(null);
  const { language } = useLanguage();

  const generatePresentation = async (settings: PresentationSettings): Promise<GeneratedPresentation | null> => {
    setIsGenerating(true);
    setGeneratedPresentation(null);

    try {
      const { data, error } = await supabase.functions.invoke('generate-presentation', {
        body: {
          ...settings,
          language
        }
      });

      if (error) {
        const status = (error as any)?.status;
        if (status === 429) {
          throw new Error(language === 'ar' ? 'تم تجاوز الحد. حاول مرة أخرى.' : 'Rate limit exceeded. Please try again.');
        }
        if (status === 402) {
          throw new Error(language === 'ar' ? 'مطلوب الدفع. الرجاء إضافة رصيد.' : 'Payment required. Please add credits.');
        }
        throw error;
      }

      if (data?.error) {
        throw new Error(data.error);
      }

      setGeneratedPresentation(data);
      return data;
    } catch (error: any) {
      console.error('Error generating presentation:', error);
      toast({
        title: language === 'ar' ? 'خطأ' : 'Error',
        description: error.message || (language === 'ar' ? 'فشل في إنشاء العرض' : 'Failed to generate presentation'),
        variant: 'destructive'
      });
      return null;
    } finally {
      setIsGenerating(false);
    }
  };

  const downloadPresentation = async (presentation: GeneratedPresentation, settings: PresentationSettings) => {
    const isArabic = language === 'ar';
    const colors = STYLE_COLORS[settings.style] || STYLE_COLORS.educational;

    try {
      const pptx = new PptxGenJS();
      pptx.author = 'Smarty Pants AI';
      pptx.title = presentation.title;
      pptx.layout = 'LAYOUT_16x9';

      // Title Slide
      const titleSlide = pptx.addSlide();
      titleSlide.addShape('rect', {
        x: 0, y: 0, w: '100%', h: '100%',
        fill: { type: 'solid', color: colors.primary }
      });
      
      // Decorative elements
      titleSlide.addShape('ellipse', {
        x: -1, y: -1, w: 4, h: 4,
        fill: { type: 'solid', color: colors.secondary }
      });
      titleSlide.addShape('ellipse', {
        x: 8, y: 3.5, w: 3, h: 3,
        fill: { type: 'solid', color: colors.accent }
      });

      titleSlide.addText(presentation.title, {
        x: 0.5, y: 2, w: 9, h: 1.5,
        fontSize: 44, bold: true, color: COLORS.white,
        align: isArabic ? 'right' : 'left'
      });

      titleSlide.addText(`${settings.gradeLevel} | ${settings.topic}`, {
        x: 0.5, y: 3.6, w: 9, h: 0.6,
        fontSize: 20, color: COLORS.light,
        align: isArabic ? 'right' : 'left'
      });

      titleSlide.addText(isArabic ? 'تم إنشاؤه بواسطة Smarty Pants AI' : 'Generated by Smarty Pants AI', {
        x: 0.5, y: 4.8, w: 9, h: 0.4,
        fontSize: 12, color: COLORS.light,
        align: isArabic ? 'right' : 'left'
      });

      // Content Slides
      presentation.slides.forEach((slide, index) => {
        const contentSlide = pptx.addSlide();

        // Header bar
        contentSlide.addShape('rect', {
          x: 0, y: 0, w: '100%', h: 1.3,
          fill: { type: 'solid', color: colors.primary }
        });

        // Slide number
        contentSlide.addShape('ellipse', {
          x: 0.3, y: 0.25, w: 0.8, h: 0.8,
          fill: { type: 'solid', color: colors.accent }
        });
        contentSlide.addText(`${index + 1}`, {
          x: 0.3, y: 0.35, w: 0.8, h: 0.6,
          fontSize: 20, bold: true, color: COLORS.white, align: 'center'
        });

        // Title
        contentSlide.addText(slide.title, {
          x: 1.3, y: 0.35, w: 8, h: 0.7,
          fontSize: 28, bold: true, color: COLORS.white,
          align: isArabic ? 'right' : 'left'
        });

        // Content bullets
        slide.content.forEach((bullet, bulletIndex) => {
          const yPos = 1.6 + bulletIndex * 0.8;
          
          // Bullet point
          contentSlide.addShape('ellipse', {
            x: isArabic ? 9.2 : 0.5, y: yPos + 0.15, w: 0.2, h: 0.2,
            fill: { type: 'solid', color: colors.secondary }
          });

          contentSlide.addText(bullet, {
            x: isArabic ? 0.5 : 0.9, y: yPos, w: 8.5, h: 0.7,
            fontSize: 18, color: COLORS.dark,
            align: isArabic ? 'right' : 'left',
            valign: 'middle'
          });
        });

        // Visual suggestion hint
        if (slide.visualSuggestion) {
          contentSlide.addShape('roundRect', {
            x: 0.5, y: 4.8, w: 9.2, h: 0.6,
            fill: { type: 'solid', color: 'F3F4F6' },
            rectRadius: 0.1
          });
          contentSlide.addText(`💡 ${isArabic ? 'اقتراح بصري: ' : 'Visual suggestion: '}${slide.visualSuggestion}`, {
            x: 0.6, y: 4.85, w: 9, h: 0.5,
            fontSize: 11, color: '6B7280', italic: true,
            align: isArabic ? 'right' : 'left'
          });
        }

        // Speaker notes
        if (slide.notes) {
          contentSlide.addNotes(slide.notes);
        }
      });

      // Quiz Slides (if included)
      if (presentation.quizQuestions && presentation.quizQuestions.length > 0) {
        // Quiz intro slide
        const quizIntro = pptx.addSlide();
        quizIntro.addShape('rect', {
          x: 0, y: 0, w: '100%', h: '100%',
          fill: { type: 'solid', color: COLORS.warning }
        });
        quizIntro.addText(isArabic ? '🎯 وقت الاختبار!' : '🎯 Quiz Time!', {
          x: 0.5, y: 2.2, w: 9, h: 1,
          fontSize: 48, bold: true, color: COLORS.white, align: 'center'
        });
        quizIntro.addText(isArabic ? 'اختبر معلوماتك' : 'Test your knowledge', {
          x: 0.5, y: 3.3, w: 9, h: 0.6,
          fontSize: 24, color: COLORS.white, align: 'center'
        });

        presentation.quizQuestions.forEach((quiz, qIndex) => {
          // Question slide
          const questionSlide = pptx.addSlide();
          questionSlide.addShape('rect', {
            x: 0, y: 0, w: '100%', h: 1.3,
            fill: { type: 'solid', color: COLORS.secondary }
          });
          questionSlide.addText(`${isArabic ? 'السؤال' : 'Question'} ${qIndex + 1}`, {
            x: 0.5, y: 0.35, w: 9, h: 0.7,
            fontSize: 24, bold: true, color: COLORS.white,
            align: isArabic ? 'right' : 'left'
          });

          questionSlide.addText(quiz.question, {
            x: 0.5, y: 1.6, w: 9.2, h: 1,
            fontSize: 22, bold: true, color: COLORS.dark,
            align: isArabic ? 'right' : 'left'
          });

          quiz.options.forEach((option, optIndex) => {
            const yPos = 2.8 + optIndex * 0.7;
            const optColors = [COLORS.primary, COLORS.secondary, COLORS.accent, COLORS.success];
            
            questionSlide.addShape('roundRect', {
              x: 0.5, y: yPos, w: 9.2, h: 0.6,
              fill: { type: 'solid', color: optColors[optIndex] },
              rectRadius: 0.1
            });
            questionSlide.addText(option, {
              x: 0.7, y: yPos + 0.1, w: 8.8, h: 0.4,
              fontSize: 16, color: COLORS.white,
              align: isArabic ? 'right' : 'left'
            });
          });

          // Answer slide
          const answerSlide = pptx.addSlide();
          answerSlide.addShape('rect', {
            x: 0, y: 0, w: '100%', h: '100%',
            fill: { type: 'solid', color: COLORS.success }
          });
          answerSlide.addText(`✅ ${isArabic ? 'الإجابة الصحيحة' : 'Correct Answer'}`, {
            x: 0.5, y: 1.5, w: 9, h: 0.8,
            fontSize: 32, bold: true, color: COLORS.white, align: 'center'
          });
          answerSlide.addText(quiz.correctAnswer, {
            x: 0.5, y: 2.5, w: 9, h: 0.8,
            fontSize: 28, bold: true, color: COLORS.white, align: 'center'
          });
          answerSlide.addShape('roundRect', {
            x: 1, y: 3.5, w: 8, h: 1.2,
            fill: { type: 'solid', color: COLORS.white },
            rectRadius: 0.1
          });
          answerSlide.addText(quiz.explanation, {
            x: 1.2, y: 3.6, w: 7.6, h: 1,
            fontSize: 16, color: COLORS.dark, align: 'center'
          });
        });
      }

      // End slide
      const endSlide = pptx.addSlide();
      endSlide.addShape('rect', {
        x: 0, y: 0, w: '100%', h: '100%',
        fill: { type: 'solid', color: colors.primary }
      });
      endSlide.addText(isArabic ? '🎉 أحسنت!' : '🎉 Great Job!', {
        x: 0.5, y: 2, w: 9, h: 1,
        fontSize: 48, bold: true, color: COLORS.white, align: 'center'
      });
      endSlide.addText(isArabic ? 'استمر في التعلم والتطور' : 'Keep learning and growing', {
        x: 0.5, y: 3.2, w: 9, h: 0.6,
        fontSize: 24, color: COLORS.light, align: 'center'
      });
      endSlide.addText('Smarty Pants AI', {
        x: 0.5, y: 4.5, w: 9, h: 0.4,
        fontSize: 14, color: COLORS.light, align: 'center'
      });

      // Download
      const filename = isArabic 
        ? `عرض_${settings.topic.replace(/\s+/g, '_')}.pptx`
        : `Presentation_${settings.topic.replace(/\s+/g, '_')}.pptx`;
      
      await pptx.writeFile({ fileName: filename });

      toast({
        title: isArabic ? 'تم التحميل!' : 'Downloaded!',
        description: isArabic ? 'تم تحميل العرض التقديمي بنجاح' : 'Presentation downloaded successfully'
      });
    } catch (error) {
      console.error('Error downloading presentation:', error);
      toast({
        title: language === 'ar' ? 'خطأ' : 'Error',
        description: language === 'ar' ? 'فشل في تحميل العرض' : 'Failed to download presentation',
        variant: 'destructive'
      });
    }
  };

  return {
    isGenerating,
    generatedPresentation,
    generatePresentation,
    downloadPresentation,
    setGeneratedPresentation
  };
};
