
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || "https://twfzlbockonxopuindaw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR3ZnpsYm9ja29ueG9wdWluZGF3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM1OTIxMzMsImV4cCI6MjA1OTE2ODEzM30.8i4PeOsf-vWuKOeukSIAJHCMYMUaraO579wvuaFzpn0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== 'undefined' ? window.localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  }
});

// Test function to check if Supabase is working
export const testSupabaseConnection = async () => {
  try {
    console.log('Testing Supabase connection...');
    
    // First try to get the session to check auth status
    const { data: authData, error: authError } = await supabase.auth.getSession();
    console.log('Auth session check:', { authData: !!authData.session, authError });
    
    // Test with a simple query that doesn't require authentication
    const { data, error, count } = await supabase
      .from('subjects')
      .select('*', { count: 'exact' })
      .limit(1);
    
    if (error) {
      console.error('Supabase connection test error:', error);
      return { success: false, error: error.message, details: error };
    }
    
    console.log('Supabase connection test successful:', { data, count });
    return { success: true, data, count };
  } catch (error: any) {
    console.error('Supabase connection test failed:', error);
    return { success: false, error: error.message };
  }
};
